#!/bin/bash
current="$(pwd)"
diff="$(git --no-pager diff --name-only master)"

find . -path '*/node_modules' -prune -o  -name 'package.json' -print0 | while IFS= read -r -d $'\0' line; do
  path="$(dirname ${line:2})"

  echo $diff | grep $path > /dev/null
  exit_status=$?

  if [[ $exit_status = 0 ]]; then
    cd $path
    yarn prepush
    exit_status=$?

    if [[ $exit_status = 1 ]]; then
      exit 1
    fi

    cd $current
  fi
done

command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.\n"; exit 2; }
git lfs pre-push "$@"