//
// This file is part of Canvas.
// Copyright (C) 2020-present  Instructure, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//

// DO NOT EDIT: this file was generated by build-colors.js

import XCTest
import SwiftUI
import UIKit
@testable import Core

class InstColorExtensionTests: XCTestCase {
    func testUIColor() {
        XCTAssertEqual(UIColor.ash, UIColor(named: "ash", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.backgroundAlert, UIColor(named: "backgroundAlert", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.backgroundDanger, UIColor(named: "backgroundDanger", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.backgroundDark, UIColor(named: "backgroundDark", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.backgroundDarkest, UIColor(named: "backgroundDarkest", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.backgroundGrouped, UIColor(named: "backgroundGrouped", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.backgroundGroupedCell, UIColor(named: "backgroundGroupedCell", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.backgroundInfo, UIColor(named: "backgroundInfo", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.backgroundLight, UIColor(named: "backgroundLight", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.backgroundLightest, UIColor(named: "backgroundLightest", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.backgroundMedium, UIColor(named: "backgroundMedium", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.backgroundSuccess, UIColor(named: "backgroundSuccess", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.backgroundWarning, UIColor(named: "backgroundWarning", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.barney, UIColor(named: "barney", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.borderAlert, UIColor(named: "borderAlert", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.borderDanger, UIColor(named: "borderDanger", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.borderDark, UIColor(named: "borderDark", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.borderDarkest, UIColor(named: "borderDarkest", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.borderInfo, UIColor(named: "borderInfo", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.borderLight, UIColor(named: "borderLight", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.borderLightest, UIColor(named: "borderLightest", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.borderMedium, UIColor(named: "borderMedium", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.borderSuccess, UIColor(named: "borderSuccess", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.borderWarning, UIColor(named: "borderWarning", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.crimson, UIColor(named: "crimson", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.electric, UIColor(named: "electric", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.fire, UIColor(named: "fire", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.licorice, UIColor(named: "licorice", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.oxford, UIColor(named: "oxford", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.porcelain, UIColor(named: "porcelain", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.shamrock, UIColor(named: "shamrock", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.tabBarBackground, UIColor(named: "tabBarBackground", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.textAlert, UIColor(named: "textAlert", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.textDanger, UIColor(named: "textDanger", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.textDark, UIColor(named: "textDark", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.textDarkest, UIColor(named: "textDarkest", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.textInfo, UIColor(named: "textInfo", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.textLight, UIColor(named: "textLight", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.textLightest, UIColor(named: "textLightest", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.textSuccess, UIColor(named: "textSuccess", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.textWarning, UIColor(named: "textWarning", in: .core, compatibleWith: nil))
        XCTAssertEqual(UIColor.tiara, UIColor(named: "tiara", in: .core, compatibleWith: nil))
    }

    func testColor() {
        XCTAssertEqual(Color.ash, Color("ash", bundle: .core))
        XCTAssertEqual(Color.backgroundAlert, Color("backgroundAlert", bundle: .core))
        XCTAssertEqual(Color.backgroundDanger, Color("backgroundDanger", bundle: .core))
        XCTAssertEqual(Color.backgroundDark, Color("backgroundDark", bundle: .core))
        XCTAssertEqual(Color.backgroundDarkest, Color("backgroundDarkest", bundle: .core))
        XCTAssertEqual(Color.backgroundGrouped, Color("backgroundGrouped", bundle: .core))
        XCTAssertEqual(Color.backgroundGroupedCell, Color("backgroundGroupedCell", bundle: .core))
        XCTAssertEqual(Color.backgroundInfo, Color("backgroundInfo", bundle: .core))
        XCTAssertEqual(Color.backgroundLight, Color("backgroundLight", bundle: .core))
        XCTAssertEqual(Color.backgroundLightest, Color("backgroundLightest", bundle: .core))
        XCTAssertEqual(Color.backgroundMedium, Color("backgroundMedium", bundle: .core))
        XCTAssertEqual(Color.backgroundSuccess, Color("backgroundSuccess", bundle: .core))
        XCTAssertEqual(Color.backgroundWarning, Color("backgroundWarning", bundle: .core))
        XCTAssertEqual(Color.barney, Color("barney", bundle: .core))
        XCTAssertEqual(Color.borderAlert, Color("borderAlert", bundle: .core))
        XCTAssertEqual(Color.borderDanger, Color("borderDanger", bundle: .core))
        XCTAssertEqual(Color.borderDark, Color("borderDark", bundle: .core))
        XCTAssertEqual(Color.borderDarkest, Color("borderDarkest", bundle: .core))
        XCTAssertEqual(Color.borderInfo, Color("borderInfo", bundle: .core))
        XCTAssertEqual(Color.borderLight, Color("borderLight", bundle: .core))
        XCTAssertEqual(Color.borderLightest, Color("borderLightest", bundle: .core))
        XCTAssertEqual(Color.borderMedium, Color("borderMedium", bundle: .core))
        XCTAssertEqual(Color.borderSuccess, Color("borderSuccess", bundle: .core))
        XCTAssertEqual(Color.borderWarning, Color("borderWarning", bundle: .core))
        XCTAssertEqual(Color.crimson, Color("crimson", bundle: .core))
        XCTAssertEqual(Color.electric, Color("electric", bundle: .core))
        XCTAssertEqual(Color.fire, Color("fire", bundle: .core))
        XCTAssertEqual(Color.licorice, Color("licorice", bundle: .core))
        XCTAssertEqual(Color.oxford, Color("oxford", bundle: .core))
        XCTAssertEqual(Color.porcelain, Color("porcelain", bundle: .core))
        XCTAssertEqual(Color.shamrock, Color("shamrock", bundle: .core))
        XCTAssertEqual(Color.tabBarBackground, Color("tabBarBackground", bundle: .core))
        XCTAssertEqual(Color.textAlert, Color("textAlert", bundle: .core))
        XCTAssertEqual(Color.textDanger, Color("textDanger", bundle: .core))
        XCTAssertEqual(Color.textDark, Color("textDark", bundle: .core))
        XCTAssertEqual(Color.textDarkest, Color("textDarkest", bundle: .core))
        XCTAssertEqual(Color.textInfo, Color("textInfo", bundle: .core))
        XCTAssertEqual(Color.textLight, Color("textLight", bundle: .core))
        XCTAssertEqual(Color.textLightest, Color("textLightest", bundle: .core))
        XCTAssertEqual(Color.textSuccess, Color("textSuccess", bundle: .core))
        XCTAssertEqual(Color.textWarning, Color("textWarning", bundle: .core))
        XCTAssertEqual(Color.tiara, Color("tiara", bundle: .core))
    }
}
