//
// This file is part of Canvas.
// Copyright (C) 2019-present  Instructure, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//

// DO NOT EDIT: this file was generated by build-icons.js

import SwiftUI
import UIKit

public extension UIImage {
    static var addLine: UIImage { UIImage(named: "addLine", in: .core, compatibleWith: nil)! }
    static var addSolid: UIImage { UIImage(named: "addSolid", in: .core, compatibleWith: nil)! }
    static var addressBookLine: UIImage { UIImage(named: "addressBookLine", in: .core, compatibleWith: nil)! }
    static var addressBookSolid: UIImage { UIImage(named: "addressBookSolid", in: .core, compatibleWith: nil)! }
    static var alertsLine: UIImage { UIImage(named: "alertsLine", in: .core, compatibleWith: nil)! }
    static var alertsSolid: UIImage { UIImage(named: "alertsSolid", in: .core, compatibleWith: nil)! }
    static var announcementLine: UIImage { UIImage(named: "announcementLine", in: .core, compatibleWith: nil)! }
    static var announcementSolid: UIImage { UIImage(named: "announcementSolid", in: .core, compatibleWith: nil)! }
    static var arrowOpenDownLine: UIImage { UIImage(named: "arrowOpenDownLine", in: .core, compatibleWith: nil)! }
    static var arrowOpenDownSolid: UIImage { UIImage(named: "arrowOpenDownSolid", in: .core, compatibleWith: nil)! }
    static var arrowOpenLeftLine: UIImage { UIImage(named: "arrowOpenLeftLine", in: .core, compatibleWith: nil)! }
    static var arrowOpenLeftSolid: UIImage { UIImage(named: "arrowOpenLeftSolid", in: .core, compatibleWith: nil)! }
    static var arrowOpenRightLine: UIImage { UIImage(named: "arrowOpenRightLine", in: .core, compatibleWith: nil)! }
    static var arrowOpenRightSolid: UIImage { UIImage(named: "arrowOpenRightSolid", in: .core, compatibleWith: nil)! }
    static var assignmentLine: UIImage { UIImage(named: "assignmentLine", in: .core, compatibleWith: nil)! }
    static var assignmentSolid: UIImage { UIImage(named: "assignmentSolid", in: .core, compatibleWith: nil)! }
    static var audioLine: UIImage { UIImage(named: "audioLine", in: .core, compatibleWith: nil)! }
    static var audioSolid: UIImage { UIImage(named: "audioSolid", in: .core, compatibleWith: nil)! }
    static var boldLine: UIImage { UIImage(named: "boldLine", in: .core, compatibleWith: nil)! }
    static var boldSolid: UIImage { UIImage(named: "boldSolid", in: .core, compatibleWith: nil)! }
    static var boxLine: UIImage { UIImage(named: "boxLine", in: .core, compatibleWith: nil)! }
    static var boxSolid: UIImage { UIImage(named: "boxSolid", in: .core, compatibleWith: nil)! }
    static var bulletListLine: UIImage { UIImage(named: "bulletListLine", in: .core, compatibleWith: nil)! }
    static var bulletListSolid: UIImage { UIImage(named: "bulletListSolid", in: .core, compatibleWith: nil)! }
    static var calendarClockLine: UIImage { UIImage(named: "calendarClockLine", in: .core, compatibleWith: nil)! }
    static var calendarClockSolid: UIImage { UIImage(named: "calendarClockSolid", in: .core, compatibleWith: nil)! }
    static var calendarMonthLine: UIImage { UIImage(named: "calendarMonthLine", in: .core, compatibleWith: nil)! }
    static var calendarMonthSolid: UIImage { UIImage(named: "calendarMonthSolid", in: .core, compatibleWith: nil)! }
    static var checkLine: UIImage { UIImage(named: "checkLine", in: .core, compatibleWith: nil)! }
    static var checkSolid: UIImage { UIImage(named: "checkSolid", in: .core, compatibleWith: nil)! }
    static var clockLine: UIImage { UIImage(named: "clockLine", in: .core, compatibleWith: nil)! }
    static var clockSolid: UIImage { UIImage(named: "clockSolid", in: .core, compatibleWith: nil)! }
    static var cloudLockLine: UIImage { UIImage(named: "cloudLockLine", in: .core, compatibleWith: nil)! }
    static var cloudLockSolid: UIImage { UIImage(named: "cloudLockSolid", in: .core, compatibleWith: nil)! }
    static var commentLine: UIImage { UIImage(named: "commentLine", in: .core, compatibleWith: nil)! }
    static var commentSolid: UIImage { UIImage(named: "commentSolid", in: .core, compatibleWith: nil)! }
    static var completeLine: UIImage { UIImage(named: "completeLine", in: .core, compatibleWith: nil)! }
    static var completeSolid: UIImage { UIImage(named: "completeSolid", in: .core, compatibleWith: nil)! }
    static var coursesLine: UIImage { UIImage(named: "coursesLine", in: .core, compatibleWith: nil)! }
    static var coursesSolid: UIImage { UIImage(named: "coursesSolid", in: .core, compatibleWith: nil)! }
    static var dashboardLine: UIImage { UIImage(named: "dashboardLine", in: .core, compatibleWith: nil)! }
    static var dashboardSolid: UIImage { UIImage(named: "dashboardSolid", in: .core, compatibleWith: nil)! }
    static var discussionLine: UIImage { UIImage(named: "discussionLine", in: .core, compatibleWith: nil)! }
    static var discussionSolid: UIImage { UIImage(named: "discussionSolid", in: .core, compatibleWith: nil)! }
    static var documentLine: UIImage { UIImage(named: "documentLine", in: .core, compatibleWith: nil)! }
    static var documentSolid: UIImage { UIImage(named: "documentSolid", in: .core, compatibleWith: nil)! }
    static var editLine: UIImage { UIImage(named: "editLine", in: .core, compatibleWith: nil)! }
    static var editSolid: UIImage { UIImage(named: "editSolid", in: .core, compatibleWith: nil)! }
    static var emailLine: UIImage { UIImage(named: "emailLine", in: .core, compatibleWith: nil)! }
    static var emailSolid: UIImage { UIImage(named: "emailSolid", in: .core, compatibleWith: nil)! }
    static var emptyLine: UIImage { UIImage(named: "emptyLine", in: .core, compatibleWith: nil)! }
    static var emptySolid: UIImage { UIImage(named: "emptySolid", in: .core, compatibleWith: nil)! }
    static var exitFullScreenLine: UIImage { UIImage(named: "exitFullScreenLine", in: .core, compatibleWith: nil)! }
    static var exitFullScreenSolid: UIImage { UIImage(named: "exitFullScreenSolid", in: .core, compatibleWith: nil)! }
    static var externalLinkLine: UIImage { UIImage(named: "externalLinkLine", in: .core, compatibleWith: nil)! }
    static var externalLinkSolid: UIImage { UIImage(named: "externalLinkSolid", in: .core, compatibleWith: nil)! }
    static var eyeLine: UIImage { UIImage(named: "eyeLine", in: .core, compatibleWith: nil)! }
    static var eyeSolid: UIImage { UIImage(named: "eyeSolid", in: .core, compatibleWith: nil)! }
    static var folderLine: UIImage { UIImage(named: "folderLine", in: .core, compatibleWith: nil)! }
    static var folderSolid: UIImage { UIImage(named: "folderSolid", in: .core, compatibleWith: nil)! }
    static var forwardLine: UIImage { UIImage(named: "forwardLine", in: .core, compatibleWith: nil)! }
    static var forwardSolid: UIImage { UIImage(named: "forwardSolid", in: .core, compatibleWith: nil)! }
    static var fullScreenLine: UIImage { UIImage(named: "fullScreenLine", in: .core, compatibleWith: nil)! }
    static var fullScreenSolid: UIImage { UIImage(named: "fullScreenSolid", in: .core, compatibleWith: nil)! }
    static var gradebookLine: UIImage { UIImage(named: "gradebookLine", in: .core, compatibleWith: nil)! }
    static var gradebookSolid: UIImage { UIImage(named: "gradebookSolid", in: .core, compatibleWith: nil)! }
    static var groupLine: UIImage { UIImage(named: "groupLine", in: .core, compatibleWith: nil)! }
    static var groupSolid: UIImage { UIImage(named: "groupSolid", in: .core, compatibleWith: nil)! }
    static var hamburgerLine: UIImage { UIImage(named: "hamburgerLine", in: .core, compatibleWith: nil)! }
    static var hamburgerSolid: UIImage { UIImage(named: "hamburgerSolid", in: .core, compatibleWith: nil)! }
    static var highlighterLine: UIImage { UIImage(named: "highlighterLine", in: .core, compatibleWith: nil)! }
    static var highlighterSolid: UIImage { UIImage(named: "highlighterSolid", in: .core, compatibleWith: nil)! }
    static var homeLine: UIImage { UIImage(named: "homeLine", in: .core, compatibleWith: nil)! }
    static var homeSolid: UIImage { UIImage(named: "homeSolid", in: .core, compatibleWith: nil)! }
    static var imageLine: UIImage { UIImage(named: "imageLine", in: .core, compatibleWith: nil)! }
    static var imageSolid: UIImage { UIImage(named: "imageSolid", in: .core, compatibleWith: nil)! }
    static var infoLine: UIImage { UIImage(named: "infoLine", in: .core, compatibleWith: nil)! }
    static var infoSolid: UIImage { UIImage(named: "infoSolid", in: .core, compatibleWith: nil)! }
    static var instructureLine: UIImage { UIImage(named: "instructureLine", in: .core, compatibleWith: nil)! }
    static var instructureSolid: UIImage { UIImage(named: "instructureSolid", in: .core, compatibleWith: nil)! }
    static var italicLine: UIImage { UIImage(named: "italicLine", in: .core, compatibleWith: nil)! }
    static var italicSolid: UIImage { UIImage(named: "italicSolid", in: .core, compatibleWith: nil)! }
    static var linkLine: UIImage { UIImage(named: "linkLine", in: .core, compatibleWith: nil)! }
    static var linkSolid: UIImage { UIImage(named: "linkSolid", in: .core, compatibleWith: nil)! }
    static var lockLine: UIImage { UIImage(named: "lockLine", in: .core, compatibleWith: nil)! }
    static var lockSolid: UIImage { UIImage(named: "lockSolid", in: .core, compatibleWith: nil)! }
    static var ltiLine: UIImage { UIImage(named: "ltiLine", in: .core, compatibleWith: nil)! }
    static var ltiSolid: UIImage { UIImage(named: "ltiSolid", in: .core, compatibleWith: nil)! }
    static var markerLine: UIImage { UIImage(named: "markerLine", in: .core, compatibleWith: nil)! }
    static var markerSolid: UIImage { UIImage(named: "markerSolid", in: .core, compatibleWith: nil)! }
    static var masteryPathsLine: UIImage { UIImage(named: "masteryPathsLine", in: .core, compatibleWith: nil)! }
    static var masteryPathsSolid: UIImage { UIImage(named: "masteryPathsSolid", in: .core, compatibleWith: nil)! }
    static var miniArrowDownLine: UIImage { UIImage(named: "miniArrowDownLine", in: .core, compatibleWith: nil)! }
    static var miniArrowDownSolid: UIImage { UIImage(named: "miniArrowDownSolid", in: .core, compatibleWith: nil)! }
    static var miniArrowEndLine: UIImage { UIImage(named: "miniArrowEndLine", in: .core, compatibleWith: nil)! }
    static var miniArrowEndSolid: UIImage { UIImage(named: "miniArrowEndSolid", in: .core, compatibleWith: nil)! }
    static var miniArrowStartLine: UIImage { UIImage(named: "miniArrowStartLine", in: .core, compatibleWith: nil)! }
    static var miniArrowStartSolid: UIImage { UIImage(named: "miniArrowStartSolid", in: .core, compatibleWith: nil)! }
    static var miniArrowUpLine: UIImage { UIImage(named: "miniArrowUpLine", in: .core, compatibleWith: nil)! }
    static var miniArrowUpSolid: UIImage { UIImage(named: "miniArrowUpSolid", in: .core, compatibleWith: nil)! }
    static var moduleLine: UIImage { UIImage(named: "moduleLine", in: .core, compatibleWith: nil)! }
    static var moduleSolid: UIImage { UIImage(named: "moduleSolid", in: .core, compatibleWith: nil)! }
    static var moreLine: UIImage { UIImage(named: "moreLine", in: .core, compatibleWith: nil)! }
    static var moreSolid: UIImage { UIImage(named: "moreSolid", in: .core, compatibleWith: nil)! }
    static var noLine: UIImage { UIImage(named: "noLine", in: .core, compatibleWith: nil)! }
    static var noSolid: UIImage { UIImage(named: "noSolid", in: .core, compatibleWith: nil)! }
    static var noteLine: UIImage { UIImage(named: "noteLine", in: .core, compatibleWith: nil)! }
    static var noteSolid: UIImage { UIImage(named: "noteSolid", in: .core, compatibleWith: nil)! }
    static var numberedListLine: UIImage { UIImage(named: "numberedListLine", in: .core, compatibleWith: nil)! }
    static var numberedListSolid: UIImage { UIImage(named: "numberedListSolid", in: .core, compatibleWith: nil)! }
    static var offLine: UIImage { UIImage(named: "offLine", in: .core, compatibleWith: nil)! }
    static var offSolid: UIImage { UIImage(named: "offSolid", in: .core, compatibleWith: nil)! }
    static var outcomesLine: UIImage { UIImage(named: "outcomesLine", in: .core, compatibleWith: nil)! }
    static var outcomesSolid: UIImage { UIImage(named: "outcomesSolid", in: .core, compatibleWith: nil)! }
    static var paintLine: UIImage { UIImage(named: "paintLine", in: .core, compatibleWith: nil)! }
    static var paintSolid: UIImage { UIImage(named: "paintSolid", in: .core, compatibleWith: nil)! }
    static var paperclipLine: UIImage { UIImage(named: "paperclipLine", in: .core, compatibleWith: nil)! }
    static var paperclipSolid: UIImage { UIImage(named: "paperclipSolid", in: .core, compatibleWith: nil)! }
    static var pauseLine: UIImage { UIImage(named: "pauseLine", in: .core, compatibleWith: nil)! }
    static var pauseSolid: UIImage { UIImage(named: "pauseSolid", in: .core, compatibleWith: nil)! }
    static var pdfLine: UIImage { UIImage(named: "pdfLine", in: .core, compatibleWith: nil)! }
    static var pdfSolid: UIImage { UIImage(named: "pdfSolid", in: .core, compatibleWith: nil)! }
    static var peerReviewLine: UIImage { UIImage(named: "peerReviewLine", in: .core, compatibleWith: nil)! }
    static var peerReviewSolid: UIImage { UIImage(named: "peerReviewSolid", in: .core, compatibleWith: nil)! }
    static var playLine: UIImage { UIImage(named: "playLine", in: .core, compatibleWith: nil)! }
    static var playSolid: UIImage { UIImage(named: "playSolid", in: .core, compatibleWith: nil)! }
    static var prerequisiteLine: UIImage { UIImage(named: "prerequisiteLine", in: .core, compatibleWith: nil)! }
    static var prerequisiteSolid: UIImage { UIImage(named: "prerequisiteSolid", in: .core, compatibleWith: nil)! }
    static var publishLine: UIImage { UIImage(named: "publishLine", in: .core, compatibleWith: nil)! }
    static var publishSolid: UIImage { UIImage(named: "publishSolid", in: .core, compatibleWith: nil)! }
    static var questionLine: UIImage { UIImage(named: "questionLine", in: .core, compatibleWith: nil)! }
    static var questionSolid: UIImage { UIImage(named: "questionSolid", in: .core, compatibleWith: nil)! }
    static var quizLine: UIImage { UIImage(named: "quizLine", in: .core, compatibleWith: nil)! }
    static var quizSolid: UIImage { UIImage(named: "quizSolid", in: .core, compatibleWith: nil)! }
    static var refreshLine: UIImage { UIImage(named: "refreshLine", in: .core, compatibleWith: nil)! }
    static var refreshSolid: UIImage { UIImage(named: "refreshSolid", in: .core, compatibleWith: nil)! }
    static var replyLine: UIImage { UIImage(named: "replyLine", in: .core, compatibleWith: nil)! }
    static var replySolid: UIImage { UIImage(named: "replySolid", in: .core, compatibleWith: nil)! }
    static var replyAllLine: UIImage { UIImage(named: "replyAllLine", in: .core, compatibleWith: nil)! }
    static var replyAllSolid: UIImage { UIImage(named: "replyAllSolid", in: .core, compatibleWith: nil)! }
    static var rubricLine: UIImage { UIImage(named: "rubricLine", in: .core, compatibleWith: nil)! }
    static var rubricSolid: UIImage { UIImage(named: "rubricSolid", in: .core, compatibleWith: nil)! }
    static var settingsLine: UIImage { UIImage(named: "settingsLine", in: .core, compatibleWith: nil)! }
    static var settingsSolid: UIImage { UIImage(named: "settingsSolid", in: .core, compatibleWith: nil)! }
    static var starLine: UIImage { UIImage(named: "starLine", in: .core, compatibleWith: nil)! }
    static var starSolid: UIImage { UIImage(named: "starSolid", in: .core, compatibleWith: nil)! }
    static var strikethroughLine: UIImage { UIImage(named: "strikethroughLine", in: .core, compatibleWith: nil)! }
    static var strikethroughSolid: UIImage { UIImage(named: "strikethroughSolid", in: .core, compatibleWith: nil)! }
    static var textLine: UIImage { UIImage(named: "textLine", in: .core, compatibleWith: nil)! }
    static var textSolid: UIImage { UIImage(named: "textSolid", in: .core, compatibleWith: nil)! }
    static var textColorLine: UIImage { UIImage(named: "textColorLine", in: .core, compatibleWith: nil)! }
    static var textColorSolid: UIImage { UIImage(named: "textColorSolid", in: .core, compatibleWith: nil)! }
    static var trashLine: UIImage { UIImage(named: "trashLine", in: .core, compatibleWith: nil)! }
    static var trashSolid: UIImage { UIImage(named: "trashSolid", in: .core, compatibleWith: nil)! }
    static var troubleLine: UIImage { UIImage(named: "troubleLine", in: .core, compatibleWith: nil)! }
    static var troubleSolid: UIImage { UIImage(named: "troubleSolid", in: .core, compatibleWith: nil)! }
    static var unlockLine: UIImage { UIImage(named: "unlockLine", in: .core, compatibleWith: nil)! }
    static var unlockSolid: UIImage { UIImage(named: "unlockSolid", in: .core, compatibleWith: nil)! }
    static var userLine: UIImage { UIImage(named: "userLine", in: .core, compatibleWith: nil)! }
    static var userSolid: UIImage { UIImage(named: "userSolid", in: .core, compatibleWith: nil)! }
    static var videoLine: UIImage { UIImage(named: "videoLine", in: .core, compatibleWith: nil)! }
    static var videoSolid: UIImage { UIImage(named: "videoSolid", in: .core, compatibleWith: nil)! }
    static var warningLine: UIImage { UIImage(named: "warningLine", in: .core, compatibleWith: nil)! }
    static var warningSolid: UIImage { UIImage(named: "warningSolid", in: .core, compatibleWith: nil)! }
    static var xLine: UIImage { UIImage(named: "xLine", in: .core, compatibleWith: nil)! }
    static var xSolid: UIImage { UIImage(named: "xSolid", in: .core, compatibleWith: nil)! }

    static var addAudioLine: UIImage { UIImage(named: "addAudioLine", in: .core, compatibleWith: nil)! }
    static var addCameraLine: UIImage { UIImage(named: "addCameraLine", in: .core, compatibleWith: nil)! }
    static var addDocumentLine: UIImage { UIImage(named: "addDocumentLine", in: .core, compatibleWith: nil)! }
    static var addImageLine: UIImage { UIImage(named: "addImageLine", in: .core, compatibleWith: nil)! }
    static var addVideoCameraLine: UIImage { UIImage(named: "addVideoCameraLine", in: .core, compatibleWith: nil)! }
    static var alertsTab: UIImage { UIImage(named: "alertsTab", in: .core, compatibleWith: nil)! }
    static var alertsTabActive: UIImage { UIImage(named: "alertsTabActive", in: .core, compatibleWith: nil)! }
    static var attendance: UIImage { UIImage(named: "attendance", in: .core, compatibleWith: nil)! }
    static var calendarEmptyLine: UIImage { UIImage(named: "calendarEmptyLine", in: .core, compatibleWith: nil)! }
    static var calendarEmptySolid: UIImage { UIImage(named: "calendarEmptySolid", in: .core, compatibleWith: nil)! }
    static var calendarTab: UIImage { UIImage(named: "calendarTab", in: .core, compatibleWith: nil)! }
    static var calendarTabActive: UIImage { UIImage(named: "calendarTabActive", in: .core, compatibleWith: nil)! }
    static var calendarTodayLine: UIImage { UIImage(named: "calendarTodayLine", in: .core, compatibleWith: nil)! }
    static var cameraLine: UIImage { UIImage(named: "cameraLine", in: .core, compatibleWith: nil)! }
    static var cameraSolid: UIImage { UIImage(named: "cameraSolid", in: .core, compatibleWith: nil)! }
    static var chatBubble: UIImage { UIImage(named: "chatBubble", in: .core, compatibleWith: nil)! }
    static var collaborations: UIImage { UIImage(named: "collaborations", in: .core, compatibleWith: nil)! }
    static var conferences: UIImage { UIImage(named: "conferences", in: .core, compatibleWith: nil)! }
    static var coursesTab: UIImage { UIImage(named: "coursesTab", in: .core, compatibleWith: nil)! }
    static var coursesTabActive: UIImage { UIImage(named: "coursesTabActive", in: .core, compatibleWith: nil)! }
    static var dashboardTab: UIImage { UIImage(named: "dashboardTab", in: .core, compatibleWith: nil)! }
    static var dashboardTabActive: UIImage { UIImage(named: "dashboardTabActive", in: .core, compatibleWith: nil)! }
    static var dropdown: UIImage { UIImage(named: "dropdown", in: .core, compatibleWith: nil)! }
    static var filterCheckbox: UIImage { UIImage(named: "filterCheckbox", in: .core, compatibleWith: nil)! }
    static var inboxTab: UIImage { UIImage(named: "inboxTab", in: .core, compatibleWith: nil)! }
    static var inboxTabActive: UIImage { UIImage(named: "inboxTabActive", in: .core, compatibleWith: nil)! }
    static var qrCode: UIImage { UIImage(named: "qrCode", in: .core, compatibleWith: nil)! }
    static var todoTab: UIImage { UIImage(named: "todoTab", in: .core, compatibleWith: nil)! }
    static var todoTabActive: UIImage { UIImage(named: "todoTabActive", in: .core, compatibleWith: nil)! }
}

public extension Icon {
    static var addLine: Icon { Icon("addLine") }
    static var addSolid: Icon { Icon("addSolid") }
    static var addressBookLine: Icon { Icon("addressBookLine") }
    static var addressBookSolid: Icon { Icon("addressBookSolid") }
    static var alertsLine: Icon { Icon("alertsLine") }
    static var alertsSolid: Icon { Icon("alertsSolid") }
    static var announcementLine: Icon { Icon("announcementLine") }
    static var announcementSolid: Icon { Icon("announcementSolid") }
    static var arrowOpenDownLine: Icon { Icon("arrowOpenDownLine") }
    static var arrowOpenDownSolid: Icon { Icon("arrowOpenDownSolid") }
    static var arrowOpenLeftLine: Icon { Icon("arrowOpenLeftLine") }
    static var arrowOpenLeftSolid: Icon { Icon("arrowOpenLeftSolid") }
    static var arrowOpenRightLine: Icon { Icon("arrowOpenRightLine") }
    static var arrowOpenRightSolid: Icon { Icon("arrowOpenRightSolid") }
    static var assignmentLine: Icon { Icon("assignmentLine") }
    static var assignmentSolid: Icon { Icon("assignmentSolid") }
    static var audioLine: Icon { Icon("audioLine") }
    static var audioSolid: Icon { Icon("audioSolid") }
    static var boldLine: Icon { Icon("boldLine") }
    static var boldSolid: Icon { Icon("boldSolid") }
    static var boxLine: Icon { Icon("boxLine") }
    static var boxSolid: Icon { Icon("boxSolid") }
    static var bulletListLine: Icon { Icon("bulletListLine") }
    static var bulletListSolid: Icon { Icon("bulletListSolid") }
    static var calendarClockLine: Icon { Icon("calendarClockLine") }
    static var calendarClockSolid: Icon { Icon("calendarClockSolid") }
    static var calendarMonthLine: Icon { Icon("calendarMonthLine") }
    static var calendarMonthSolid: Icon { Icon("calendarMonthSolid") }
    static var checkLine: Icon { Icon("checkLine") }
    static var checkSolid: Icon { Icon("checkSolid") }
    static var clockLine: Icon { Icon("clockLine") }
    static var clockSolid: Icon { Icon("clockSolid") }
    static var cloudLockLine: Icon { Icon("cloudLockLine") }
    static var cloudLockSolid: Icon { Icon("cloudLockSolid") }
    static var commentLine: Icon { Icon("commentLine") }
    static var commentSolid: Icon { Icon("commentSolid") }
    static var completeLine: Icon { Icon("completeLine") }
    static var completeSolid: Icon { Icon("completeSolid") }
    static var coursesLine: Icon { Icon("coursesLine") }
    static var coursesSolid: Icon { Icon("coursesSolid") }
    static var dashboardLine: Icon { Icon("dashboardLine") }
    static var dashboardSolid: Icon { Icon("dashboardSolid") }
    static var discussionLine: Icon { Icon("discussionLine") }
    static var discussionSolid: Icon { Icon("discussionSolid") }
    static var documentLine: Icon { Icon("documentLine") }
    static var documentSolid: Icon { Icon("documentSolid") }
    static var editLine: Icon { Icon("editLine") }
    static var editSolid: Icon { Icon("editSolid") }
    static var emailLine: Icon { Icon("emailLine") }
    static var emailSolid: Icon { Icon("emailSolid") }
    static var emptyLine: Icon { Icon("emptyLine") }
    static var emptySolid: Icon { Icon("emptySolid") }
    static var exitFullScreenLine: Icon { Icon("exitFullScreenLine") }
    static var exitFullScreenSolid: Icon { Icon("exitFullScreenSolid") }
    static var externalLinkLine: Icon { Icon("externalLinkLine") }
    static var externalLinkSolid: Icon { Icon("externalLinkSolid") }
    static var eyeLine: Icon { Icon("eyeLine") }
    static var eyeSolid: Icon { Icon("eyeSolid") }
    static var folderLine: Icon { Icon("folderLine") }
    static var folderSolid: Icon { Icon("folderSolid") }
    static var forwardLine: Icon { Icon("forwardLine") }
    static var forwardSolid: Icon { Icon("forwardSolid") }
    static var fullScreenLine: Icon { Icon("fullScreenLine") }
    static var fullScreenSolid: Icon { Icon("fullScreenSolid") }
    static var gradebookLine: Icon { Icon("gradebookLine") }
    static var gradebookSolid: Icon { Icon("gradebookSolid") }
    static var groupLine: Icon { Icon("groupLine") }
    static var groupSolid: Icon { Icon("groupSolid") }
    static var hamburgerLine: Icon { Icon("hamburgerLine") }
    static var hamburgerSolid: Icon { Icon("hamburgerSolid") }
    static var highlighterLine: Icon { Icon("highlighterLine") }
    static var highlighterSolid: Icon { Icon("highlighterSolid") }
    static var homeLine: Icon { Icon("homeLine") }
    static var homeSolid: Icon { Icon("homeSolid") }
    static var imageLine: Icon { Icon("imageLine") }
    static var imageSolid: Icon { Icon("imageSolid") }
    static var infoLine: Icon { Icon("infoLine") }
    static var infoSolid: Icon { Icon("infoSolid") }
    static var instructureLine: Icon { Icon("instructureLine") }
    static var instructureSolid: Icon { Icon("instructureSolid") }
    static var italicLine: Icon { Icon("italicLine") }
    static var italicSolid: Icon { Icon("italicSolid") }
    static var linkLine: Icon { Icon("linkLine") }
    static var linkSolid: Icon { Icon("linkSolid") }
    static var lockLine: Icon { Icon("lockLine") }
    static var lockSolid: Icon { Icon("lockSolid") }
    static var ltiLine: Icon { Icon("ltiLine") }
    static var ltiSolid: Icon { Icon("ltiSolid") }
    static var markerLine: Icon { Icon("markerLine") }
    static var markerSolid: Icon { Icon("markerSolid") }
    static var masteryPathsLine: Icon { Icon("masteryPathsLine") }
    static var masteryPathsSolid: Icon { Icon("masteryPathsSolid") }
    static var miniArrowDownLine: Icon { Icon("miniArrowDownLine") }
    static var miniArrowDownSolid: Icon { Icon("miniArrowDownSolid") }
    static var miniArrowEndLine: Icon { Icon("miniArrowEndLine") }
    static var miniArrowEndSolid: Icon { Icon("miniArrowEndSolid") }
    static var miniArrowStartLine: Icon { Icon("miniArrowStartLine") }
    static var miniArrowStartSolid: Icon { Icon("miniArrowStartSolid") }
    static var miniArrowUpLine: Icon { Icon("miniArrowUpLine") }
    static var miniArrowUpSolid: Icon { Icon("miniArrowUpSolid") }
    static var moduleLine: Icon { Icon("moduleLine") }
    static var moduleSolid: Icon { Icon("moduleSolid") }
    static var moreLine: Icon { Icon("moreLine") }
    static var moreSolid: Icon { Icon("moreSolid") }
    static var noLine: Icon { Icon("noLine") }
    static var noSolid: Icon { Icon("noSolid") }
    static var noteLine: Icon { Icon("noteLine") }
    static var noteSolid: Icon { Icon("noteSolid") }
    static var numberedListLine: Icon { Icon("numberedListLine") }
    static var numberedListSolid: Icon { Icon("numberedListSolid") }
    static var offLine: Icon { Icon("offLine") }
    static var offSolid: Icon { Icon("offSolid") }
    static var outcomesLine: Icon { Icon("outcomesLine") }
    static var outcomesSolid: Icon { Icon("outcomesSolid") }
    static var paintLine: Icon { Icon("paintLine") }
    static var paintSolid: Icon { Icon("paintSolid") }
    static var paperclipLine: Icon { Icon("paperclipLine") }
    static var paperclipSolid: Icon { Icon("paperclipSolid") }
    static var pauseLine: Icon { Icon("pauseLine") }
    static var pauseSolid: Icon { Icon("pauseSolid") }
    static var pdfLine: Icon { Icon("pdfLine") }
    static var pdfSolid: Icon { Icon("pdfSolid") }
    static var peerReviewLine: Icon { Icon("peerReviewLine") }
    static var peerReviewSolid: Icon { Icon("peerReviewSolid") }
    static var playLine: Icon { Icon("playLine") }
    static var playSolid: Icon { Icon("playSolid") }
    static var prerequisiteLine: Icon { Icon("prerequisiteLine") }
    static var prerequisiteSolid: Icon { Icon("prerequisiteSolid") }
    static var publishLine: Icon { Icon("publishLine") }
    static var publishSolid: Icon { Icon("publishSolid") }
    static var questionLine: Icon { Icon("questionLine") }
    static var questionSolid: Icon { Icon("questionSolid") }
    static var quizLine: Icon { Icon("quizLine") }
    static var quizSolid: Icon { Icon("quizSolid") }
    static var refreshLine: Icon { Icon("refreshLine") }
    static var refreshSolid: Icon { Icon("refreshSolid") }
    static var replyLine: Icon { Icon("replyLine") }
    static var replySolid: Icon { Icon("replySolid") }
    static var replyAllLine: Icon { Icon("replyAllLine") }
    static var replyAllSolid: Icon { Icon("replyAllSolid") }
    static var rubricLine: Icon { Icon("rubricLine") }
    static var rubricSolid: Icon { Icon("rubricSolid") }
    static var settingsLine: Icon { Icon("settingsLine") }
    static var settingsSolid: Icon { Icon("settingsSolid") }
    static var starLine: Icon { Icon("starLine") }
    static var starSolid: Icon { Icon("starSolid") }
    static var strikethroughLine: Icon { Icon("strikethroughLine") }
    static var strikethroughSolid: Icon { Icon("strikethroughSolid") }
    static var textLine: Icon { Icon("textLine") }
    static var textSolid: Icon { Icon("textSolid") }
    static var textColorLine: Icon { Icon("textColorLine") }
    static var textColorSolid: Icon { Icon("textColorSolid") }
    static var trashLine: Icon { Icon("trashLine") }
    static var trashSolid: Icon { Icon("trashSolid") }
    static var troubleLine: Icon { Icon("troubleLine") }
    static var troubleSolid: Icon { Icon("troubleSolid") }
    static var unlockLine: Icon { Icon("unlockLine") }
    static var unlockSolid: Icon { Icon("unlockSolid") }
    static var userLine: Icon { Icon("userLine") }
    static var userSolid: Icon { Icon("userSolid") }
    static var videoLine: Icon { Icon("videoLine") }
    static var videoSolid: Icon { Icon("videoSolid") }
    static var warningLine: Icon { Icon("warningLine") }
    static var warningSolid: Icon { Icon("warningSolid") }
    static var xLine: Icon { Icon("xLine") }
    static var xSolid: Icon { Icon("xSolid") }
}
