//
//  PSPDFGlyph.h
//  PSPDFKit
//
//  Copyright (c) 2012-2016 PSPDFKit GmbH. All rights reserved.
//
//  THIS SOURCE CODE AND ANY ACCOMPANYING DOCUMENTATION ARE PROTECTED BY INTERNATIONAL COPYRIGHT LAW
//  AND MAY NOT BE RESOLD OR REDISTRIBUTED. USAGE IS BOUND TO THE PSPDFKIT LICENSE AGREEMENT.
//  UNAUTHORIZED REPRODUCTION OR DISTRIBUTION IS SUBJECT TO CIVIL AND CRIMINAL PENALTIES.
//  This notice may not be removed from this file.
//

#import <Foundation/Foundation.h>
#import "PSPDFMacros.h"

/// Default padding factor added to the glyph rects in `PSPDFBoundingBoxFromGlyphs` and `PSPDFRectsFromGlyphs`
/// to improve selection appearance. The padding factor is multiplied by the frame height and the width and height extended
/// by that value.
PSPDF_EXPORT const CGFloat PSPDFDefaultTextPaddingFactor;

NS_ASSUME_NONNULL_BEGIN

/// Represents a single character (glyph, quad) on the PDF page.
/// @note Glyphs are created from the PDF contents and not meant to be created manually.
PSPDF_CLASS_AVAILABLE_SUBCLASSING_RESTRICTED @interface PSPDFGlyph : NSObject <NSCopying, NSSecureCoding>

PSPDF_EMPTY_INIT_UNAVAILABLE

/// Frame of the glyph. Doesn't have `rotation` applied.
/// To apply the rotation, use `CGRectApplyAffineTransform(glyph.frame, pageView.pageInfo.rotationTransform)`
/// (`PSPDFWord` etc do have convenience methods for this)
@property (nonatomic, readonly) CGRect frame;

/// Character content (usually a single character)
@property (nonatomic, copy, readonly) NSString *content;

/// Set if after this glyph a \\n is there.
@property (nonatomic, readonly) BOOL lineBreaker;

/// Dynamically evaluated. Return YES if glyph is a word boundary (space, parenthesis)
@property (nonatomic, readonly) BOOL isWordBreaker;

/// Returns YES if glyph is end of a word or line.
@property (nonatomic, readonly) BOOL isWordOrLineBreaker;

/// Index set on the glyph, or -1 for autogenerated fillers.
/// @note This is not meant to identify glyphs. Get the `glyphs` array from the text parser and call `indexOfObjectIdenticalTo:` on it.
@property (nonatomic, readonly) NSInteger indexOnPage;

@end

/// Converts an array of glyphs to a string.
PSPDF_EXPORT NSString *PSPDFStringFromGlyphs(NSArray<PSPDFGlyph *> *_Nullable glyphs);

/// Returns the bounding box that includes all glyphs.
/// `t` is the `rotationTransform` of `PSPDFPageInfo`.
/// @return Rect encompassing all glyphs or CGRectZero if glyphs is empty.
PSPDF_EXPORT CGRect PSPDFBoundingBoxFromGlyphs(NSArray<PSPDFGlyph *> *_Nullable glyphs, NSInteger pageRotation);

/// Global helper to convert glyphs to rects.
/// `t` is `the rotationTransform` of `PSPDFPageInfo`.
/// `boundingBox` will already be transformed with `t`.
PSPDF_EXPORT NSArray<NSValue *> *PSPDFRectsFromGlyphs(NSArray<PSPDFGlyph *> *_Nullable glyphs, CGRect *boundingBox, NSInteger pageRotation);

NS_ASSUME_NONNULL_END
