//
//  PSPDFPrivateKey.h
//  PSPDFKit
//
//  Copyright © 2013-2017 PSPDFKit GmbH. All rights reserved.
//
//  THIS SOURCE CODE AND ANY ACCOMPANYING DOCUMENTATION ARE PROTECTED BY INTERNATIONAL COPYRIGHT LAW
//  AND MAY NOT BE RESOLD OR REDISTRIBUTED. USAGE IS BOUND TO THE PSPDFKIT LICENSE AGREEMENT.
//  UNAUTHORIZED REPRODUCTION OR DISTRIBUTION IS SUBJECT TO CIVIL AND CRIMINAL PENALTIES.
//  This notice may not be removed from this file.
//

#import "PSPDFEnvironment.h"

NS_ASSUME_NONNULL_BEGIN

PSPDF_CLASS_AVAILABLE_SUBCLASSING_RESTRICTED @interface PSPDFPrivateKey : NSObject

PSPDF_EMPTY_INIT_UNAVAILABLE

/// The encryption algorithm used in this private key.
@property (nonatomic, readonly) NSString *encryptionAlgorithm;

@end

NS_ASSUME_NONNULL_END
