//
//  PSPDFDataContainerProvider.h
//  PSPDFModel
//
//  Copyright (c) 2015-2016 PSPDFKit GmbH. All rights reserved.
//
//  THIS SOURCE CODE AND ANY ACCOMPANYING DOCUMENTATION ARE PROTECTED BY INTERNATIONAL COPYRIGHT LAW
//  AND MAY NOT BE RESOLD OR REDISTRIBUTED. USAGE IS BOUND TO THE PSPDFKIT LICENSE AGREEMENT.
//  UNAUTHORIZED REPRODUCTION OR DISTRIBUTION IS SUBJECT TO CIVIL AND CRIMINAL PENALTIES.
//  This notice may not be removed from this file.
//

#import "PSPDFEnvironment.h"
#import "PSPDFDataProvider.h"

NS_ASSUME_NONNULL_BEGIN

/// A `PSPDFDataProvider` that operates on a single `NSData`.
PSPDF_CLASS_AVAILABLE_SUBCLASSING_RESTRICTED @interface PSPDFDataContainerProvider : NSObject <PSPDFDataProvider>

PSPDF_EMPTY_INIT_UNAVAILABLE

- (instancetype)initWithData:(NSData *)data NS_DESIGNATED_INITIALIZER;

@end

NS_ASSUME_NONNULL_END
