//
//  PSPDFAnnotationGroupItem.h
//  PSPDFKit
//
//  Copyright © 2014-2017 PSPDFKit GmbH. All rights reserved.
//
//  THIS SOURCE CODE AND ANY ACCOMPANYING DOCUMENTATION ARE PROTECTED BY INTERNATIONAL COPYRIGHT LAW
//  AND MAY NOT BE RESOLD OR REDISTRIBUTED. USAGE IS BOUND TO THE PSPDFKIT LICENSE AGREEMENT.
//  UNAUTHORIZED REPRODUCTION OR DISTRIBUTION IS SUBJECT TO CIVIL AND CRIMINAL PENALTIES.
//  This notice may not be removed from this file.
//

#import "PSPDFAnnotation.h"
#import "PSPDFEnvironment.h"
#import "PSPDFModel.h"

NS_ASSUME_NONNULL_BEGIN

@class PSPDFAnnotationGroupItem;
typedef UIImage *_Nonnull (^PSPDFAnnotationGroupItemConfigurationBlock)(PSPDFAnnotationGroupItem *item, id _Nullable container, UIColor *tintColor);

PSPDF_EXPORT PSPDFAnnotationString const PSPDFAnnotationStringInkVariantPen;
PSPDF_EXPORT PSPDFAnnotationString const PSPDFAnnotationStringInkVariantHighlighter;
PSPDF_EXPORT PSPDFAnnotationString const PSPDFAnnotationStringLineVariantArrow;
PSPDF_EXPORT PSPDFAnnotationString const PSPDFAnnotationStringFreeTextVariantCallout;

/// Simple helper that combines a state + variant into a new identifier.
/// Can be used to set custom types in the `PSPDFStyleManager`.
PSPDF_EXPORT PSPDFAnnotationString PSPDFAnnotationStateVariantIdentifier(PSPDFAnnotationString, PSPDFAnnotationString _Nullable variant);

/// Returns the original annotation state from a string that previously has been generated by `PSPDFAnnotationStateVariantIdentifier`.
PSPDF_EXPORT PSPDFAnnotationString PSPDFAnnotationStateFromStateVariantIdentifier(PSPDFAnnotationString);

/// An annotation group items defines one annotation type, optionally with a variant.
PSPDF_CLASS_AVAILABLE_SUBCLASSING_RESTRICTED @interface PSPDFAnnotationGroupItem : PSPDFModel

PSPDF_EMPTY_INIT_UNAVAILABLE

/// Creates a group item with the specified annotation type.
/// @see itemWithType:variant:configurationBlock:
+ (instancetype)itemWithType:(PSPDFAnnotationString)type;

/// Creates a group item with the specified annotation type and optional variant identifier.
/// @see itemWithType:variant:configurationBlock:
+ (instancetype)itemWithType:(PSPDFAnnotationString)type variant:(nullable PSPDFAnnotationString)variant;

/// Creates a group item with the specified annotation type, an optional variant identifier and configuration block.
/// @param type The annotation type.
/// @param variant An optional annotation string for the item variant. Use variants to add several instances of the same tool with uniquely preservable annotation style settings.
/// @param block An option block, that should return the button's image. If nil, `defaultConfigurationBlock` is used.
/// @note Whenever possible try to return a template image from the configuration block (UIImageRenderingModeAlwaysTemplate). Use the provided tint color only when you need multi-color images.
+ (instancetype)itemWithType:(PSPDFAnnotationString)type variant:(nullable PSPDFAnnotationString)variant configurationBlock:(PSPDFAnnotationGroupItemConfigurationBlock)block;

/// A block that configures an preset image based on the annotation type.
/// This is the default configuration block.
+ (PSPDFAnnotationGroupItemConfigurationBlock)defaultConfigurationBlock;

/// The set annotation type.
@property (nonatomic, copy, readonly) PSPDFAnnotationString type;

/// The annotation variant, if set during initialization.
@property (nonatomic, copy, readonly, nullable) PSPDFAnnotationString variant;

/// Used to generate the annotation image. Will be `defaultConfigurationBlock` or `inkConfigurationBlock` in most cases.
@property (nonatomic, copy, readonly) PSPDFAnnotationGroupItemConfigurationBlock configurationBlock;

@end

NS_ASSUME_NONNULL_END
