//
// This file is part of Canvas.
// Copyright (C) 2026-present  Instructure, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//

const StyleDictionary = require('style-dictionary')

const fileHeader = 
`//
// This file is part of Canvas.
// Copyright (C) 2026-present  Instructure, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//`

StyleDictionary.registerFormat({
  name: 'swiftui/primitives-colors',
  formatter: ({ dictionary }) => {
    const colorTokens = dictionary.allTokens.filter(t => t.path[0] === 'color')

    // Canonical Color declarations — hex lives here and nowhere else
    const colorProperties = colorTokens
      .map(t => {
        const name = t.path[t.path.length - 1]
        const hex = t.value.toUpperCase()
        const displayHex = hex.length === 9 && hex.endsWith('FF') ? hex.slice(0, 7) : hex
        return `    static let ${name} = Color(hex: "${displayHex}")`
      })
      .join('\n')

    const allEntries = colorTokens
      .map(t => {
        const name = t.path[t.path.length - 1]
        return `        ("${name}", ${name})`
      })
      .join(',\n')

    // Color extension — forwards to primitives, no hex duplication
    const colorExtProps = colorTokens
      .map(t => {
        const name = t.path[t.path.length - 1]
        return `            public static let ${name} = InstUI.Primitives.Colors.${name}`
      })
      .join('\n')

    // UIColor extension — wraps Color values via type-inferred dot syntax, no hex duplication
    const uiColorExtProps = colorTokens
      .map(t => {
        const name = t.path[t.path.length - 1]
        return `            public static let ${name} = UIColor(.instui.primitives.${name})`
      })
      .join('\n')

    const colorExtensions =
`public extension Color {

    /// Access primitive colors via \`Color.instui.primitives.navy120\`
    enum instui {
        public enum primitives {
${colorExtProps}
        }
    }
}

public extension UIColor {

    /// Access primitive colors via \`UIColor.instui.primitives.navy120\`
    enum instui {
        public enum primitives {
${uiColorExtProps}
        }
    }
}`

    return [
      fileHeader,
      '',
      'import SwiftUI',
      'import UIKit',
      '',
      '// DO NOT EDIT — Auto-generated by `yarn build-instui`',
      'public extension InstUI.Primitives.Colors {',
      colorProperties,
      '',
      '    static let all: [(name: String, color: Color)] = [',
      allEntries,
      '    ]',
      '}',
      '',
      colorExtensions,
      ''
    ].join('\n')
  }
})

StyleDictionary.registerFormat({
  name: 'swiftui/primitives-sizes',
  formatter: ({ dictionary }) => {
    const sizeTokens = dictionary.allTokens
      .filter(t => t.path[0] === 'size' || t.path[0] === 'additionalSize')
      .sort((a, b) => parseFloat(a.value) - parseFloat(b.value))

    const sizeProperties = sizeTokens
      .map(t => {
        const name = t.path[t.path.length - 1]
        const points = parseFloat(t.value) * 16
        return `    static let ${name}: CGFloat = ${points}`
      })
      .join('\n')

    const allEntries = sizeTokens
      .map(t => {
        const name = t.path[t.path.length - 1]
        return `        ("${name}", ${name})`
      })
      .join(',\n')

    const sizeExtProps = sizeTokens
      .map(t => {
        const name = t.path[t.path.length - 1]
        return `            public static let ${name} = InstUI.Primitives.Sizes.${name}`
      })
      .join('\n')

    const sizeExtension =
`public extension CGFloat {

    /// Access primitive sizes via \`CGFloat.instui.primitives.size16\`
    enum instui {
        public enum primitives {
${sizeExtProps}
        }
    }
}`

    return [
      fileHeader,
      '',
      'import CoreGraphics',
      '',
      '// DO NOT EDIT — Auto-generated by `yarn build-instui`',
      'public extension InstUI.Primitives.Sizes {',
      sizeProperties,
      '',
      '    static let all: [(name: String, size: CGFloat)] = [',
      allEntries,
      '    ]',
      '}',
      '',
      sizeExtension,
      ''
    ].join('\n')
  }
})

StyleDictionary.registerFormat({
  name: 'swiftui/primitives-font-weights',
  formatter: ({ dictionary }) => {
    const weightMap = {
      '100': '.ultraLight',
      '200': '.thin',
      '300': '.light',
      '400': '.regular',
      '500': '.medium',
      '600': '.semibold',
      '700': '.bold',
      '800': '.heavy',
      '900': '.black'
    }

    const weightTokens = dictionary.allTokens.filter(t => t.path[0] === 'fontWeight')

    const weightProperties = weightTokens
      .map(t => {
        const name = t.path[t.path.length - 1]
        const swiftWeight = weightMap[String(t.value)]
        return `    static let ${name}: Font.Weight = ${swiftWeight}`
      })
      .join('\n')

    const allEntries = weightTokens
      .map(t => {
        const name = t.path[t.path.length - 1]
        return `        ("${name}", ${name})`
      })
      .join(',\n')

    const weightExtProps = weightTokens
      .map(t => {
        const name = t.path[t.path.length - 1]
        return `            public static let ${name} = InstUI.Primitives.FontWeights.${name}`
      })
      .join('\n')

    const weightExtension =
`public extension Font.Weight {

    /// Access primitive font weights via \`Font.Weight.instui.primitives.semiBold\`
    enum instui {
        public enum primitives {
${weightExtProps}
        }
    }
}`

    return [
      fileHeader,
      '',
      'import SwiftUI',
      '',
      '// DO NOT EDIT — Auto-generated by `yarn build-instui`',
      'public extension InstUI.Primitives.FontWeights {',
      weightProperties,
      '',
      '    static let all: [(name: String, weight: Font.Weight)] = [',
      allEntries,
      '    ]',
      '}',
      '',
      weightExtension,
      ''
    ].join('\n')
  }
})

StyleDictionary.registerFormat({
  name: 'swiftui/primitives-opacities',
  formatter: ({ dictionary }) => {
    const opacityTokens = dictionary.allTokens
      .filter(t => t.path[0].startsWith('opacity'))
      .sort((a, b) => parseFloat(a.value) - parseFloat(b.value))

    const opacityProperties = opacityTokens
      .map(t => {
        const name = t.path[t.path.length - 1]
        return `    static let ${name}: Double = ${parseFloat(t.value)}`
      })
      .join('\n')

    const allEntries = opacityTokens
      .map(t => {
        const name = t.path[t.path.length - 1]
        return `        ("${name}", ${name})`
      })
      .join(',\n')

    const opacityExtProps = opacityTokens
      .map(t => {
        const name = t.path[t.path.length - 1]
        return `            public static let ${name} = InstUI.Primitives.Opacities.${name}`
      })
      .join('\n')

    const opacityExtension =
`public extension Double {

    /// Access primitive opacities via \`Double.instui.primitives.opacity50\`
    enum instui {
        public enum primitives {
${opacityExtProps}
        }
    }
}`

    return [
      fileHeader,
      '',
      '// DO NOT EDIT — Auto-generated by `yarn build-instui`',
      'public extension InstUI.Primitives.Opacities {',
      opacityProperties,
      '',
      '    static let all: [(name: String, opacity: Double)] = [',
      allEntries,
      '    ]',
      '}',
      '',
      opacityExtension,
      ''
    ].join('\n')
  }
})

StyleDictionary.registerFormat({
  name: 'swiftui/primitives-font-families',
  formatter: ({ dictionary }) => {
    const familyTokens = dictionary.allTokens.filter(t => t.path[0] === 'fontFamily')

    const familyProperties = familyTokens
      .map(t => {
        const name = t.path[t.path.length - 1]
        const firstFont = t.value.split(',')[0].trim().replace(/"/g, '')
        return `    static let ${name}: String = { _ = _registered; return "${firstFont}" }()`
      })
      .join('\n')

    const allEntries = familyTokens
      .map(t => {
        const name = t.path[t.path.length - 1]
        return `        ("${name}", ${name})`
      })
      .join(',\n')

    const familyExtProps = familyTokens
      .map(t => {
        const name = t.path[t.path.length - 1]
        const prefixed = 'font' + name.charAt(0).toUpperCase() + name.slice(1)
        return `            public static let ${prefixed} = InstUI.Primitives.FontFamilies.${name}`
      })
      .join('\n')

    const familyExtension =
`public extension String {

    /// Access primitive font families via \`String.instui.primitives.fontLato\`
    enum instui {
        public enum primitives {
${familyExtProps}
        }
    }
}`

    // Triggers font registration exactly once when any font family is first accessed.
    // Private to the extension block — each font string property references it in its closure.
    const registrationTrigger = '    private static let _registered: Void = FontRegistration.registerFonts()'

    return [
      fileHeader,
      '',
      '// DO NOT EDIT — Auto-generated by `yarn build-instui`',
      'public extension InstUI.Primitives.FontFamilies {',
      registrationTrigger,
      '',
      familyProperties,
      '',
      '    static let all: [(name: String, family: String)] = [',
      allEntries,
      '    ]',
      '}',
      '',
      familyExtension,
      ''
    ].join('\n')
  }
})

module.exports = function buildConfig(tokens) {
  return StyleDictionary.extend({
    tokens,
    platforms: {
      swift: {
        transforms: ['attribute/cti', 'color/hex8'],
        buildPath: 'packages/InstUI/Sources/InstUI/Sources/Primitives/',
        files: [
          {
            destination: 'InstUI.Primitives.Colors.swift',
            format: 'swiftui/primitives-colors'
          },
          {
            destination: 'InstUI.Primitives.Sizes.swift',
            format: 'swiftui/primitives-sizes'
          },
          {
            destination: 'InstUI.Primitives.FontWeights.swift',
            format: 'swiftui/primitives-font-weights'
          },
          {
            destination: 'InstUI.Primitives.Opacities.swift',
            format: 'swiftui/primitives-opacities'
          },
          {
            destination: 'InstUI.Primitives.FontFamilies.swift',
            format: 'swiftui/primitives-font-families'
          }
        ]
      }
    }
  })
}
