//
// This file is part of Canvas.
// Copyright (C) 2026-present  Instructure, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//

const StyleDictionary = require('style-dictionary')

const fileHeader = 
`//
// This file is part of Canvas.
// Copyright (C) 2026-present  Instructure, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//`

const colorExtension =
`extension Color {

    /// Supports the following syntax: \`.foregroundStyle(.instui.primitives.navy120)\`
    enum instui {
        static let primitives = InstUI.Primitives.Colors()
    }
}`

StyleDictionary.registerFormat({
  name: 'swiftui/primitives-colors',
  formatter: ({ dictionary }) => {
    const colorTokens = dictionary.allTokens.filter(t => t.path[0] === 'color')

    const properties = colorTokens
      .map(t => {
        const name = t.path[t.path.length - 1]
        const hex = t.value.toUpperCase()
        const displayHex = hex.length === 9 && hex.endsWith('FF') ? hex.slice(0, 7) : hex
        return `        public let ${name} = Color(hex: "${displayHex}")`
      })
      .join('\n')

    return [
      fileHeader,
      '',
      'import SwiftUI',
      '',
      '// DO NOT EDIT — Auto-generated by \`yarn build-instui\`',
      'public extension InstUI.Primitives {',
      '    struct Colors: Sendable {',
      properties,
      '    }',
      '}',
      '',
      colorExtension,
      ''
    ].join('\n')
  }
})

module.exports = function buildConfig(tokens) {
  return StyleDictionary.extend({
    tokens,
    platforms: {
      swift: {
        transforms: ['attribute/cti', 'color/hex8'],
        buildPath: 'packages/InstUI/Sources/InstUI/Sources/Primitives/',
        files: [
          {
            destination: 'InstUI.Primitives.Colors.swift',
            format: 'swiftui/primitives-colors'
          }
        ]
      }
    }
  })
}
