disabled_rules: # rule identifiers to exclude from running
  - control_statement
  - class_delegate_protocol
  - todo
  - identifier_name
  - force_try
  - nesting
  - force_cast
  - xctfail_message
  - type_body_length
  - file_length
  - unused_setter_value
  - type_name
opt_in_rules: # some rules are only opt-in
  - yoda_condition
included: # paths to include during linting. `--path` is ignored if present.
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

trailing_comma:
  mandatory_comma: false
