//
//  PSPDFRSAKey.h
//  PSPDFKit
//
//  Copyright (c) 2013-2016 PSPDFKit GmbH. All rights reserved.
//
//  THIS SOURCE CODE AND ANY ACCOMPANYING DOCUMENTATION ARE PROTECTED BY INTERNATIONAL COPYRIGHT LAW
//  AND MAY NOT BE RESOLD OR REDISTRIBUTED. USAGE IS BOUND TO THE PSPDFKIT LICENSE AGREEMENT.
//  UNAUTHORIZED REPRODUCTION OR DISTRIBUTION IS SUBJECT TO CIVIL AND CRIMINAL PENALTIES.
//  This notice may not be removed from this file.
//

#import "PSPDFEnvironment.h"

NS_ASSUME_NONNULL_BEGIN

typedef void *OPENSSL_EVP_PKEY;

PSPDF_CLASS_AVAILABLE_SUBCLASSING_RESTRICTED @interface PSPDFRSAKey : NSObject

PSPDF_EMPTY_INIT_UNAVAILABLE

/// Initializes from an OpenSSL EVP_PKEY object.
- (instancetype)initWithKey:(OPENSSL_EVP_PKEY)key NS_DESIGNATED_INITIALIZER;

/// Returns the OpenSSL private key.
@property (nonatomic, readonly) OPENSSL_EVP_PKEY pKey;

@end

NS_ASSUME_NONNULL_END

