disabled_rules: # rule identifiers to exclude from running
  - control_statement
  - class_delegate_protocol
  - todo
  - nesting
  - cyclomatic_complexity
  - file_length
  - type_body_length
  - identifier_name
  - function_parameter_count
  - multiple_closures_with_trailing_closure
  - inclusive_language
  - non_optional_string_data_conversion # Can be re-enabled when https://github.com/realm/SwiftLint/pull/5601 is merged back.
opt_in_rules: # some rules are only opt-in
  - yoda_condition
included: # paths to include during linting. `--path` is ignored if present.
  - Core
  - Student
  - rn/Teacher/ios
  - Parent
  - TestsFoundation
  - scripts/swift
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Canvas # Student/Canvas

line_length:
  warning: 200
  ignores_comments: true
function_body_length: 100

large_tuple:
  warning: 4
  error: 4

type_name:
  min_length: 3
  max_length: 50

trailing_comma:
  mandatory_comma: true
