---
name: Horizon
options:
  groupSortPosition: top
  bundleIdPrefix: com.instructure.horizon
  deploymentTarget:
    iOS: 17.0
  createIntermediateGroups: true
configFiles:
  Debug: Horizon/Config/Debug.xcconfig
  Release: Horizon/Config/Release.xcconfig
settings:
  CODE_SIGN_STYLE: Automatic ## This line is removed in the project-ci.yml file so Bitrise can manage code sign.
  DEVELOPMENT_TEAM: B6333T4PXQ ## This line is removed in the project-ci.yml file so Bitrise can manage code sign.
  CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: true
  LOCALIZATION_PREFERS_STRING_CATALOGS: true
  CURRENT_PROJECT_VERSION: 0.0.1
  MARKETING_VERSION: 0.0.1
  platform: iOS
  CODE_SIGN_ENTITLEMENTS: Horizon/Resources/Horizon.entitlements
sources:
  - path: ./
    excludes:
      - ".swiftlint.yml"
  - path: ../packages
include:
  - Horizon/horizon.yml
projectReferences:
  Core:
    path: ../Core/Core.xcodeproj
packages:
  # Local
  HorizonUI:
    path: ../packages/HorizonUI

  # Remote
  Heap:
    url: https://github.com/heap/heap-ios-sdk.git
    exactVersion: 9.1.0
  PSPDFKit:
    url: https://github.com/PSPDFKit/PSPDFKit-SP
    exactVersion: 13.9.1
  FirebaseCrashlytics:
    url: https://github.com/firebase/firebase-ios-sdk.git
    exactVersion: 10.23.1
  FirebaseRemoteConfig:
    url: https://github.com/firebase/firebase-ios-sdk.git
    exactVersion: 10.23.1
  FirebaseRemoteConfigSwift:
    url: https://github.com/firebase/firebase-ios-sdk.git
    exactVersion: 10.23.1
