//
// Copyright (C) 2016-present Instructure, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

import ReactiveSwift
import Result

open class Dispatcher<Input, Output, E: Error> {
	fileprivate let executeClosure: (Input) -> SignalProducer<Output, E>
	fileprivate let eventsObserver: Signal<Event<Output, E>, NoError>.Observer

	/// A signal of all events generated from applications of the Dispatcher.
	///
	/// In other words, this will send every `Event` from every signal generated
	/// by each SignalProducer returned from apply().
	open let events: Signal<Event<Output, E>, NoError>

	/// A signal of all values generated from applications of the Dispatcher.
	///
	/// In other words, this will send every value from every signal generated
	/// by each SignalProducer returned from apply().
	open let values: Signal<Output, NoError>

	/// A signal of all errors generated from applications of the Dispatcher.
	///
	/// In other words, this will send errors from every signal generated by
	/// each SignalProducer returned from apply().
	open let errors: Signal<E, NoError>

	public init(execute: @escaping (Input) -> SignalProducer<Output, E>) {
        executeClosure = execute
		(events, eventsObserver) = Signal<Event<Output, E>, NoError>.pipe()

		values = events.map { $0.value }.skipNil()
		errors = events.map { $0.error }.skipNil()
    }

	/// Creates a SignalProducer that, when started, will dispatch the input
	/// then forward the results upon the produced Signal.
	///
	/// - parameters:
	///   - input: A value that will be passed to the closure creating the signal
	///            producer.
	
	open func apply(_ input: Input) -> SignalProducer<Output, E> {
		return SignalProducer { observer, disposable in
			self.executeClosure(input).startWithSignal { signal, signalDisposable in
				disposable.add(signalDisposable)

				signal.observe { event in
					observer.action(event)
                    self.eventsObserver.send(value: event)
				}
			}
		}
    }
}
