//
// This file is part of Canvas.
// Copyright (C) 2024-present  Instructure, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//

import SwiftUI

public extension HorizonUI {
     struct Icons: Sendable {
        fileprivate init() {}

        let accessibilityNew = Image(.accessibilityNew)
        let accountCircle = Image(.accountCircle)
        let add = Image(.add)
        let addAlert = Image(.addAlert)
        let addCircle = Image(.addCircle)
        let addLink = Image(.addLink)
        let addNotes = Image(.addNotes)
        let addTask = Image(.addTask)
        let addToDrive = Image(.addToDrive)
        let adsClick = Image(.adsClick)
        let alarm = Image(.alarm)
        let alignHorizontalLeft = Image(.alignHorizontalLeft)
        let allInclusive = Image(.allInclusive)
        let api = Image(.api)
        let appRegistratoin = Image(.appRegistratoin)
        let apps = Image(.apps)
        let archive = Image(.archive)
        let arrowLeftAlt = Image(.arrowLeftAlt)
        let arrowRightAlt = Image(.arrowRightAlt)

        let arrowUpwardAlt = Image(.arrowUpwardAlt)
        let arrowForward = Image(.arrowForward)
        let arrowBack = Image(.arrowBack)
        let arrowBackIosNewChevronLeft = Image(.arrowBackIosNewChevronLeft)
        let arrowUpward = Image(.arrowUpward)
        let arrowDownward = Image(.arrowDownward)
        let arrowForwardIosChevronRight = Image(.arrowForwardIosChevronRight)
        let chevronLeft = Image(.chevronLeft)
        let chevronRight = Image(.chevronRight)
        let arrowCircleDown = Image(.arrowCircleDown)
        let arrowCircleLeft = Image(.arrowCircleLeft)
        let arrowCircleRight = Image(.arrowCircleRight)
        let arrowCircleUp = Image(.arrowCircleUp)
        let arrowDropDown = Image(.arrowDropDown)
        let arrowDropUp = Image(.arrowDropUp)
        let arrowLeft = Image(.arrowLeft)
        let arrowRight = Image(.arrowRight)
        let arrowTopLeft = Image(.arrowTopLeft)
        let arrowTopRight = Image(.arrowTopRight)
        let article = Image(.article)

        let attachFile = Image(.attachFile)
        let attachment = Image(.attachment)
        let autorenew = Image(.autorenew)
        let backspace = Image(.backspace)
        let backup = Image(.backup)
        let ballot = Image(.ballot)
        let block = Image(.block)
        let bolt = Image(.bolt)
        let book4 = Image(.book4)
        let book4Spark = Image(.book4Spark)
        let bookmarkAdd = Image(.bookmarkAdd)
        let book5 = Image(.book5)
        let bookmark = Image(.bookmark)
        let bookmarks = Image(.bookmarks)
        let borderColor = Image(.iconBorder)
        let browse = Image(.browse)
        let bugReport = Image(.bugReport)
        let build = Image(.build)
        let buildCircle = Image(.buildCircle)
        let cached = Image(.cached)

        let calendarMonth = Image(.calendarMonth)
        let calendarToday = Image(.calendarToday)
        let calendarViewMonth = Image(.calendarViewMonth)
        let cancel = Image(.cancel)
        let category = Image(.category)
        let celebration = Image(.celebration)
        let changeCircle = Image(.changeCircle)
        let changeHistory = Image(.changeHistory)
        let chat = Image(.chat)
        let checkBoxOutlineBlank = Image(.checkBoxOutlineBlank)
        let check = Image(.check)
        let checkSmall = Image(.checkSmall)
        let checkBox = Image(.checkBox)
        let checkCircle = Image(.checkCircle)
        let checklist = Image(.checklist)
        let checklistRtl = Image(.checklistRtl)
        let close = Image(.close)
        let closeSmall = Image(.closeSmall)
        let closeFullscren = Image(.closeFullscren)
        let cloud = Image(.cloud)

        let cloudDone = Image(.cloudDone)
        let cloudDownload = Image(.cloudDownload)
        let cloudOff = Image(.cloudOff)
        let cloudSync = Image(.cloudSync)
        let cloudUpload = Image(.cloudUpload)
        let code = Image(.code)
        let collectionsBookmark = Image(.collectionsBookmark)
        let compareArrows = Image(.compareArrows)
        let contactPage = Image(.contactPage)
        let contentCopy = Image(.contentCopy)
        let contentCut = Image(.contentCut)
        let contentPaste = Image(.contentPaste)
        let contentPasteGo = Image(.contentPasteGo)
        let contentPasteSearch = Image(.contentPasteSearch)
        let copyAll = Image(.copyAll)
        let counter1 = Image(.counter1)
        let counter2 = Image(.counter2)
        let counter3 = Image(.counter3)
        let counter4 = Image(.counter4)
        let counter5 = Image(.counter5)

        let counter6 = Image(.counter6)
        let counter7 = Image(.counter7)
        let counter8 = Image(.counter8)
        let counter9 = Image(.counter9)
        let createNewFolder = Image(.createNewFolder)
        let dangerous = Image(.dangerous)
        let dashboard = Image(.dashboard)
        let dashboardCustomize = Image(.dashboardCustomize)
        let dataObject = Image(.dataObject)
        let dataset = Image(.dataset)
        let dateRange = Image(.dateRange)
        let delete = Image(.delete)
        let deleteForever = Image(.deleteForever)
        let description = Image(.description)
        let designServices = Image(.designServices)
        let dictionary = Image(.dictionary)
        let difference = Image(.difference)
        let disabledByDefault = Image(.disabledByDefault)
        let doNotDisturbOn = Image(.doNotDisturbOn)
        let docs = Image(.docs)

        let docsAddOn = Image(.docsAddOn)
        let documentScanner = Image(.documentScanner)
        let doneAll = Image(.doneAll)
        let doneOutline = Image(.doneOutline)
        let doubleArrow = Image(.doubleArrow)
        let download = Image(.download)
        let downloadForOffline = Image(.downloadForOffline)
        let downloading = Image(.downloading)
        let draft = Image(.draft)
        let dragHandle = Image(.dragHandle)
        let dragIndicator = Image(.dragIndicator)
        let dragPan = Image(.dragPan)
        let draw = Image(.draw)
        let driveFileMove = Image(.driveFileMove)
        let driveFolderUpload = Image(.driveFolderUpload)
        let editCalendar = Image(.editCalendar)
        let editDocument = Image(.editDocument)
        let editNote = Image(.editNote)
        let editOff = Image(.editOff)
        let editSquare = Image(.editSquare)

        let keyboardDoubleArrowLeft = Image(.keyboardDoubleArrowLeft)
        let error = Image(.error)
        let event = Image(.event)
        let eventAvailable = Image(.eventAvailable)
        let eventBusy = Image(.eventBusy)
        let eventNote = Image(.eventNote)
        let eventUpcoming = Image(.eventUpcoming)
        let exitToApp = Image(.exitToApp)
        let expandCircleUp = Image(.expandCircleUp)
        let expandCircleDown = Image(.expandCircleDown)
        let `extension` = Image(.extension)
        let factCheck = Image(.factCheck)
        let favorite = Image(.favorite)
        let fileCopy = Image(.fileCopy)
        let fileOpen = Image(.fileOpen)
        let filePresent = Image(.filePresent)
        let filterAlt = Image(.filterAlt)
        let filterList = Image(.filterList)
        let findInPage = Image(.findInPage)
        let fingerprint = Image(.fingerprint)

        let firstPage = Image(.firstPage)
        let folder = Image(.folder)
        let folderCheck = Image(.folderCheck)
        let folderCheck2 = Image(.folderCheck2)
        let folderCopy = Image(.folderCopy)
        let folderDelete = Image(.folderDelete)
        let folderOpen = Image(.folderOpen)
        let folderShared = Image(.folderShared)
        let folderSpecial = Image(.folderSpecial)
        let folderZip = Image(.folderZip)
        let fontDownload = Image(.fontDownload)
        let formatAlignCenter = Image(.formatAlignCenter)
        let formatAlignJustify = Image(.formatAlignJustify)
        let formatAlignLeft = Image(.formatAlignLeft)
        let formatAlignRight = Image(.formatAlignRight)
        let formatBold = Image(.formatBold)
        let formatColorFill = Image(.formatColorFill)
        let formatColorReset = Image(.formatColorReset)
        let formatColorText = Image(.formatColorText)
        let formatIndentIncrease = Image(.formatIndentIncrease)

        let formatItalic = Image(.formatItalic)
        let formatLineSpacing = Image(.formatLineSpacing)
        let coursesFormatListBulleted = Image(.coursesFormatListBulleted)
        let formatListNumbered = Image(.formatListNumbered)
        let formatListNumberedRtl = Image(.formatListNumberedRtl)
        let formatPaint = Image(.formatPaint)
        let formatParagraph = Image(.formatParagraph)
        let formatQuote = Image(.formatQuote)
        let formatShapes = Image(.formatShapes)
        let formatSize = Image(.formatSize)
        let formatUnderlined = Image(.formatUnderlined)
        let formsAddOn = Image(.formsAddOn)
        let forward = Image(.forward)
        let fullscreen = Image(.fullscreen)
        let fullscreenExit = Image(.fullscreenExit)
        let functions = Image(.functions)
        let grade = Image(.grade)
        let grading = Image(.grading)
        let gridView = Image(.gridView)
        let height = Image(.height)

        let help = Image(.help)
        let helpCenter = Image(.helpCenter)
        let history = Image(.history)
        let historyEdu = Image(.historyEdu)
        let home = Image(.home)
        let hourglassEmpty = Image(.hourglassEmpty)
        let howToReg = Image(.howToReg)
        let indeterminateCheckBox = Image(.indeterminateCheckBox)
        let info = Image(.info)
        let inkHighlighter = Image(.inkHighlighter)
        let inkPen = Image(.inkPen)
        let integrationInstructions = Image(.integrationInstructions)
        let interests = Image(.interests)
        let inventory = Image(.inventory)
        let iosShare = Image(.iosShare)
        let key = Image(.key)
        let horizontalRule = Image(.horizontalRule)
        let keyboardArrowDown = Image(.keyboardArrowDown)
        let keyboardArrowUp = Image(.keyboardArrowUp)
        let keyboardDoubleArrowDown = Image(.keyboardDoubleArrowDown)

        let keyboardDoubleArrowRight = Image(.keyboardDoubleArrowRight)
        let keyboardDoubleArrowUp = Image(.keyboardDoubleArrowUp)
        let label = Image(.label)
        let labelImportant = Image(.labelImportant)
        let language = Image(.language)
        let libraryAdd = Image(.libraryAdd)
        let lightbulb = Image(.lightbulb)
        let linearScale = Image(.linearScale)
        let list = Image(.list)
        let listAlt = Image(.listAlt)
        let lock = Image(.lock)
        let lockOpen = Image(.lockOpen)
        let login = Image(.login)
        let logout = Image(.logout)
        let lowPriority = Image(.lowPriority)
        let mail = Image(.mail)
        let manageAccounts = Image(.manageAccounts)
        let manageSearch = Image(.manageSearch)
        let markEmailUnread = Image(.markEmailUnread)
        let matchCase = Image(.matchCase)

        let menu = Image(.menu)
        let minimize = Image(.minimize)
        let moreHoriz = Image(.moreHoriz)
        let moreTime = Image(.moreTime)
        let moreVert = Image(.moreVert)
        let newLabel = Image(.newLabel)
        let newReleases = Image(.newReleases)
        let news = Image(.news)
        let newspaper = Image(.newspaper)
        let noteAdd = Image(.noteAdd)
        let noteAlt = Image(.noteAlt)
        let notes = Image(.notes)
        let notificationAdd = Image(.notificationAdd)
        let notificationImportant = Image(.notificationImportant)
        let notificationsActive = Image(.notificationsActive)
        let numbers = Image(.numbers)
        let openInFull = Image(.openInFull)
        let openInNew = Image(.openInNew)
        let openWith = Image(.openWith)
        let pages = Image(.pages)

        let pageview = Image(.pageview)
        let panToolAlt = Image(.panToolAlt)
        let pending = Image(.pending)
        let pendingActions = Image(.pendingActions)
        let percent = Image(.percent)
        let permMedia = Image(.permMedia)
        let plagiarism = Image(.plagiarism)
        let postAdd = Image(.postAdd)
        let powerSettingsNew = Image(.powerSettingsNew)
        let preview = Image(.preview)
        let priority = Image(.priority)
        let priorityHigh = Image(.priorityHigh)
        let publish = Image(.publish)
        let publishedWithChanges = Image(.publishedWithChanges)
        let questionMark = Image(.questionMark)
        let radioButtonChecked = Image(.radioButtonChecked)
        let radioButtonUnchecked = Image(.radioButtonUnchecked)
        let readMore = Image(.readMore)
        let recordVoiceOver = Image(.recordVoiceOver)
        let redo = Image(.redo)

        let refresh = Image(.refresh)
        let remove = Image(.remove)
        let reorder = Image(.reorder)
        let reply = Image(.reply)
        let replyAll = Image(.replyAll)
        let restartAlt = Image(.restartAlt)
        let restorePage = Image(.restorePage)
        let rule = Image(.rule)
        let saveAs = Image(.saveAs)
        let schedule = Image(.schedule)
        let segment = Image(.segment)
        let selectCheckBox = Image(.selectCheckBox)
        let send = Image(.send)
        let settingsAccessibility = Image(.settingsAccessibility)
        let settingsApplications = Image(.settingsApplications)
        let shoppingCartCheckout = Image(.shoppingCartCheckout)
        let sort = Image(.sort)
        let sortByAlpha = Image(.sortByAlpha)
        let spaceBar = Image(.spaceBar)
        let spellcheck = Image(.spellcheck)

        let square = Image(.square)
        let stacks = Image(.stacks)
        let star = Image(.star)
        let starHalf = Image(.starHalf)
        let stars = Image(.stars)
        let start = Image(.start)
        let stickyNote2 = Image(.stickyNote2)
        let subject = Image(.subject)
        let summarize = Image(.summarize)
        let support = Image(.support)
        let swapHoriz = Image(.swapHoriz)
        let swapVert = Image(.swapVert)
        let switchAccessShortcut = Image(.switchAccessShortcut)
        let sync = Image(.sync)
        let syncAlt = Image(.syncAlt)
        let table = Image(.table)
        let tableChart = Image(.tableChart)
        let tableRows = Image(.tableRows)
        let tableView = Image(.tableView)
        let tag = Image(.tag)

        let task = Image(.task)
        let taskAlt = Image(.taskAlt)
        let teamDashboard = Image(.teamDashboard)
        let textDecrease = Image(.textDecrease)
        let textFields = Image(.textFields)
        let textFormat = Image(.textFormat)
        let textIncrease = Image(.textIncrease)
        let textSelectStart = Image(.textSelectStart)
        let textSnippet = Image(.textSnippet)
        let title = Image(.title)
        let toc = Image(.toc)
        let today = Image(.today)
        let toggleOff = Image(.toggleOff)
        let toggleOn = Image(.toggleOn)
        let touchApp = Image(.touchApp)
        let translate = Image(.translate)
        let undo = Image(.undo)
        let unfoldMore = Image(.unfoldMore)
        let update = Image(.update)
        let upgrade = Image(.upgrade)

        let upload = Image(.upload)
        let uploadFile = Image(.uploadFile)
        let verified = Image(.verified)
        let verticalAlignBottom = Image(.verticalAlignBottom)
        let verticalAlignCenter = Image(.verticalAlignCenter)
        let verticalAlignTop = Image(.verticalAlignTop)
        let videoFile = Image(.videoFile)
        let viewAgenda = Image(.viewAgenda)
        let viewCarousel = Image(.viewCarousel)
        let viewColumn = Image(.viewColumn)
        let viewHeadline = Image(.viewHeadline)
        let viewList = Image(.viewList)
        let viewModule = Image(.viewModule)
        let viewWeek = Image(.viewWeek)
        let visibility = Image(.visibility)
        let visibilityOff = Image(.visibilityOff)
        let warning = Image(.warning)
        let web = Image(.web)
        let webAsset = Image(.webAsset)
        let wysiwyg = Image(.wysiwyg)

        let zoomIn = Image(.zoomIn)
        let zoomOut = Image(.zoomOut)
        let search = Image(.search)
        let careersConversionPath = Image(.careersConversionPath)
        let quiz = Image(.quiz)
        let editDocumentAssignment = Image(.editDocumentAssignment)
        let draftFile = Image(.draftFile)
        let articlePage = Image(.articlePage)
        let forumDiscussion = Image(.forumDiscussion)
        let notificationsUnread = Image(.notificationsUnread)
        let volumeUp = Image(.volumeUp)
        let flag2 = Image(.flag2)
        let checkCircleFull = Image(.checkCircleFull)
        let edit = Image(.edit)
        let link = Image(.link)
        let image = Image(.image)
        let videocam = Image(.videocam)

        let thumbUp = Image(.thumbUp)
        let thumbDown = Image(.thumbDown)
        let keepPin = Image(.keepPin)
        let book2Filled = Image(.book2Filled)
        let book2 = Image(.book2)
        let hub = Image(.hub)
        let hubFilled = Image(.hubFilled)
        let circlesExtFilled = Image(.circlesExtFilled)
        let circlesExt = Image(.circlesExt)
        let widgets = Image(.widgets)
        let widgetsFilled = Image(.widgetsFilled)
        let accountCircleFilled = Image(.accountCircleFilled)
        let homeFilled = Image(.homeFilled)
        let circleFilled = Image(.circleFilled)
        let circle = Image(.circle)

        func allImages() -> [Image] {
            let mirror = Mirror(reflecting: self)
            return mirror.children.compactMap { $0.value as? Image }
        }
    }
    
    static let icons = HorizonUI.Icons()
}

extension Image {
    static let huiIcons = HorizonUI.icons
}
