version: 2.1

commands:
  bootstrap:
    steps:
      - run:
          name: Setup CI environment
          command: |
            set -ex
            set -o pipefail
            cd $CIRCLE_WORKING_DIRECTORY
            make bootstrap-ci
            make sync-ci
  setup-app-secrets-student:
    steps:
      - run:
          name: Setup App Secrets
          command: |
            git clone git@github.com:instructure/steps-canvas-ios-secrets.git                        
            steps-canvas-ios-secrets/scripts/setup-student-secrets.sh
  setup-gservice-key:
    steps:
      - run:
          name: Setup Google Service Key
          command: |
            base64 --decode > ${HOME}/gservice-key.json
jobs:
  unit-test-all:
    macos:
      xcode: "16.1"
    resource_class: m2pro.medium
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - bootstrap
      - run:
          name: Run CITests
          command: |
            bundle exec fastlane unit_test_all
  build-adhoc-student:
    macos:
      xcode: "16.1"
    resource_class: m2pro.medium
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - bootstrap
      - setup-gservice-key
      - setup-app-secrets-student
      - run: 
          name: Run fastlane adhoc_student
          command: |
            bundle exec fastlane adhoc_student
      - store_artifacts:
          path: output

workflows:
  pr-workflow:
    jobs:
      - unit-test-all:      
      - build-adhoc-student:
          filters:
            branches:
              only:
                - circleci-project-setup

