version: 2.1

commands:
  bootstrap:
    steps:
      - run:
          name: Setup CI environment
          command: |
            set -ex
            set -o pipefail
            cd $CIRCLE_WORKING_DIRECTORY
            make bootstrap-ci
            make sync-ci
  setup_app_secrets_student:
    steps:
      - run:
          name: Setup App Secrets
          command: |
            git clone git@github.com:instructure/steps-canvas-ios-secrets.git                        
            ./steps-canvas-ios-secrets/scripts/setup-student-secrets.sh
  setup_gservice_key:
    steps:
      - run:
          name: Setup Google Service Key
          command: |
            echo $GSERVICE_KEY | base64 --decode > ${HOME}/gservice-key.json
jobs:
  unit_test_all:
    macos:
      xcode: "16.1"
    resource_class: m2pro.medium
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - bootstrap
      - run:
          name: Run CITests
          command: |
            bundle exec fastlane unit_test_all
      - store_artifacts:
          path: ./output
      - store_test_results:
          path: ./output/unit_test_all_report.xml
  build_adhoc_student:
    macos:
      xcode: "16.1"
    resource_class: m2pro.medium
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - bootstrap
      - setup_gservice_key
      - setup_app_secrets_student
      - run: 
          name: Run fastlane adhoc_student
          command: |
            bundle exec fastlane adhoc_student
      - store_artifacts:
          path: output

workflows:
  pr_workflow:
    jobs:
      - unit_test_all     
      - build_adhoc_student:
          filters:
            branches:
              only:
                - circleci-project-setup

