version: 2.1

executors:
  default_executor:
    macos:
      xcode: 16.1
      resource_class: macos.m1.large.gen1

orbs:
  macos: circleci/macos@2

commands:
  bootstrap:
    steps:
      - run:
          name: Setup CI environment
          command: |
            set -ex
            set -o pipefail
            cd $CIRCLE_WORKING_DIRECTORY
            make bootstrap-ci
            make sync-ci
  setup_app_secrets_dev:
    steps:
      - run:
          name: Setup App Secrets
          command: |
            git clone git@github.com:instructure/steps-canvas-ios-secrets.git                        
            ./steps-canvas-ios-secrets/scripts/setup-dev-secrets.sh
  setup_app_secrets_student:
    steps:
      - run:
          name: Setup App Secrets
          command: |
            git clone git@github.com:instructure/steps-canvas-ios-secrets.git                        
            ./steps-canvas-ios-secrets/scripts/setup-student-secrets.sh
  setup_gservice_key:
    steps:
      - run:
          name: Setup Google Service Key
          command: |
            echo $GSERVICE_KEY | base64 --decode > ${HOME}/gservice-key.json
jobs:
  unit_tests:
    executor:
      name: default_executor
    environment:
      FL_OUTPUT_DIR: ./fastlane_results
    steps:
      - checkout
      - bootstrap
      - run:
          name: Danger
          command: |
            yarn danger ci
      - run:
          name: Run CITests
          command: |
            bundle exec fastlane unit_tests
      - store_test_results:
          path: ./reports/unit_tests_results.xml
  build_e2e_tests_student:
    executor:
      name: default_executor
    steps:
      - checkout
      - bootstrap
      - run: 
          name: Build E2ETests-Student
          command: |
            bundle exec fastlane e2e_tests_student_build_only
      - persist_to_workspace:
          root: .
          paths:
            - dist
      - store_artifacts:
          path: ./artifacts
  e2e_tests_student:
#    parallelism: 4
    executor:
      name: default_executor
    environment:
      FL_OUTPUT_DIR: ./fastlane_results
    steps:
      - checkout
      - bootstrap      
      - setup_app_secrets_dev
      - macos/preboot-simulator:
          device: iPhone 16
          version: "18.1"
      - attach_workspace:
          at: .
      - run:
          name: Run E2ETests-Student
          command: |
            bundle exec fastlane e2e_tests_student
#            CLASSNAMES=$(circleci tests glob "Student/StudentE2ETests/**/*.swift" \
#              | sed 's@/@.@g' \
#              | sed 's/.swift//' \
#              | circleci tests split --split-by=timings --timings-type=classname)
#            FASTLANE_ARGS=$(echo $CLASSNAMES | sed -e 's/\./\//g' -e 's/ /,/g')
#            echo $CLASSNAMES
#            bundle exec fastlane e2e_tests_student tests:$FASTLANE_ARGS
      - store_artifacts:
          path: ./artifacts
      - store_test_results:
          path: ./reports/e2e_tests_student.xml
  publish_student_firebase:
    executor:
      name: default_executor
    environment:
      FL_OUTPUT_DIR: ./fastlane_results
    steps:
      - checkout
      - bootstrap
      - setup_gservice_key
      - setup_app_secrets_student
      - run: 
          name: Publish Student to Firebase
          command: |
            bundle exec fastlane publish_student_firebase
      - store_artifacts:
          path: ./artifacts

workflows:
  pr_workflow:
    jobs:      
      - unit_tests
      - publish_student_firebase:
          filters:
            branches:
              only:
                - circleci-project-setup
  nightly:
    jobs:
      - hold:
          type: approval
      - build_e2e_tests_student:
          requires:
            - hold
      - e2e_tests_student:
          requires:
            - build_e2e_tests_student
