version: 2.1

commands:
  bootstrap:
    steps:
      - run:
          name: Setup CI environment
          command: |
            set -ex
            set -o pipefail
            cd $CIRCLE_WORKING_DIRECTORY
            make bootstrap-ci
      - run:
          name: Run make sync
          command: |
            set -ex
            set -o pipefail
            cd $CIRCLE_WORKING_DIRECTORY
            make sync-ci
  setup-app-secrets-student:
    steps:
      - run:
          name: Add Canvas iOS Secrets
          command: |
            git clone git@github.com:instructure/steps-canvas-ios-secrets.git                        
            steps-canvas-ios-secrets/scripts/setup-student-secrets.sh
  setup-gcloud-key:
    steps:
      - run:
          name: Decode and save Google Credentials
          command: |
            echo $GSERVICE_KEY | base64 --decode > ${HOME}/gservice-key.json

jobs:
  build-adhoc-student:
    macos:
      xcode: "16.1"
    resource_class: m2pro.medium
    environment:
      FL_OUTPUT_DIR: output
      BITRISE_CONFIGURATION: "Adhoc"
      BITRISE_SCHEME: "Student"
    steps:
      - checkout
      - bootstrap
      - setup-gcloud-key
      - setup-app-secrets-student
      - run: bundle exec fastlane adhoc_student
      - store_artifacts:
          path: output

workflows:
  pr-workflow:
    jobs:
      - build-adhoc-student:
          filters:
            branches:
              only:
                - circleci-project-setup

