//
// This file is part of Canvas.
// Copyright (C) 2026-present  Instructure, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//

import SwiftUI

// DO NOT EDIT — Auto-generated by `yarn build-instui`
public extension InstUI.Primitives.FontWeights {
    static let thin: Font.Weight = .ultraLight
    static let extraLight: Font.Weight = .thin
    static let light: Font.Weight = .light
    static let regular: Font.Weight = .regular
    static let medium: Font.Weight = .medium
    static let semiBold: Font.Weight = .semibold
    static let bold: Font.Weight = .bold
    static let extraBold: Font.Weight = .heavy
    static let black: Font.Weight = .black

    static let all: [(name: String, weight: Font.Weight)] = [
        ("thin", thin),
        ("extraLight", extraLight),
        ("light", light),
        ("regular", regular),
        ("medium", medium),
        ("semiBold", semiBold),
        ("bold", bold),
        ("extraBold", extraBold),
        ("black", black)
    ]
}

extension Font.Weight {

    /// Access primitive font weights via `Font.Weight.instui.primitives.semiBold`
    enum instui {
        enum primitives {
            static let thin = InstUI.Primitives.FontWeights.thin
            static let extraLight = InstUI.Primitives.FontWeights.extraLight
            static let light = InstUI.Primitives.FontWeights.light
            static let regular = InstUI.Primitives.FontWeights.regular
            static let medium = InstUI.Primitives.FontWeights.medium
            static let semiBold = InstUI.Primitives.FontWeights.semiBold
            static let bold = InstUI.Primitives.FontWeights.bold
            static let extraBold = InstUI.Primitives.FontWeights.extraBold
            static let black = InstUI.Primitives.FontWeights.black
        }
    }
}
