//
// This file is part of Canvas.
// Copyright (C) 2026-present  Instructure, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//

import CoreGraphics

// DO NOT EDIT — Auto-generated by `yarn build-instui`
public extension InstUI.Primitives.Sizes {
    static let size1: CGFloat = 1
    static let size1_25: CGFloat = 1.25
    static let size1_5: CGFloat = 1.5
    static let size2: CGFloat = 2
    static let size2_5: CGFloat = 2.5
    static let size3: CGFloat = 3
    static let size4: CGFloat = 4
    static let size8: CGFloat = 8
    static let size12: CGFloat = 12
    static let size14: CGFloat = 14
    static let size16: CGFloat = 16
    static let size20: CGFloat = 20
    static let size24: CGFloat = 24
    static let size28: CGFloat = 28
    static let size32: CGFloat = 32
    static let size36: CGFloat = 36
    static let size40: CGFloat = 40
    static let size48: CGFloat = 48
    static let size64: CGFloat = 64

    static let all: [(name: String, size: CGFloat)] = [
        ("size1", size1),
        ("size1_25", size1_25),
        ("size1_5", size1_5),
        ("size2", size2),
        ("size2_5", size2_5),
        ("size3", size3),
        ("size4", size4),
        ("size8", size8),
        ("size12", size12),
        ("size14", size14),
        ("size16", size16),
        ("size20", size20),
        ("size24", size24),
        ("size28", size28),
        ("size32", size32),
        ("size36", size36),
        ("size40", size40),
        ("size48", size48),
        ("size64", size64)
    ]
}

extension CGFloat {

    /// Access primitive sizes via `CGFloat.instui.primitives.size16`
    enum instui {
        enum primitives {
            static let size1 = InstUI.Primitives.Sizes.size1
            static let size1_25 = InstUI.Primitives.Sizes.size1_25
            static let size1_5 = InstUI.Primitives.Sizes.size1_5
            static let size2 = InstUI.Primitives.Sizes.size2
            static let size2_5 = InstUI.Primitives.Sizes.size2_5
            static let size3 = InstUI.Primitives.Sizes.size3
            static let size4 = InstUI.Primitives.Sizes.size4
            static let size8 = InstUI.Primitives.Sizes.size8
            static let size12 = InstUI.Primitives.Sizes.size12
            static let size14 = InstUI.Primitives.Sizes.size14
            static let size16 = InstUI.Primitives.Sizes.size16
            static let size20 = InstUI.Primitives.Sizes.size20
            static let size24 = InstUI.Primitives.Sizes.size24
            static let size28 = InstUI.Primitives.Sizes.size28
            static let size32 = InstUI.Primitives.Sizes.size32
            static let size36 = InstUI.Primitives.Sizes.size36
            static let size40 = InstUI.Primitives.Sizes.size40
            static let size48 = InstUI.Primitives.Sizes.size48
            static let size64 = InstUI.Primitives.Sizes.size64
        }
    }
}
