//
// This file is part of Canvas.
// Copyright (C) 2026-present  Instructure, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//

// DO NOT EDIT — Auto-generated by `yarn build-instui`
public extension InstUI.Primitives.FontFamilies {
    private static let _registered: Void = FontRegistration.registerFonts()

    static let lato: String = { _ = _registered; return "Lato" }()
    static let inclusiveSans: String = { _ = _registered; return "Inclusive Sans" }()
    static let atkinson: String = { _ = _registered; return "Atkinson Hyperlegible Next" }()
    static let menlo: String = { _ = _registered; return "Menlo" }()

    static let all: [(name: String, family: String)] = [
        ("lato", lato),
        ("inclusiveSans", inclusiveSans),
        ("atkinson", atkinson),
        ("menlo", menlo)
    ]
}

public extension String {

    /// Access primitive font families via `String.instui.primitives.fontLato`
    enum instui {
        public enum primitives {
            public static let fontLato = InstUI.Primitives.FontFamilies.lato
            public static let fontInclusiveSans = InstUI.Primitives.FontFamilies.inclusiveSans
            public static let fontAtkinson = InstUI.Primitives.FontFamilies.atkinson
            public static let fontMenlo = InstUI.Primitives.FontFamilies.menlo
        }
    }
}
