//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: feature_flags.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import Dispatch
import SwiftGRPC
import SwiftProtobuf

public protocol Soseedy_SeedyFeatureFlagsSetAccountFeatureFlagCall: ClientCallUnary {}

fileprivate final class Soseedy_SeedyFeatureFlagsSetAccountFeatureFlagCallBase: ClientCallUnaryBase<Soseedy_SetAccountFeatureFlagRequest, Soseedy_FeatureFlag>, Soseedy_SeedyFeatureFlagsSetAccountFeatureFlagCall {
  override class var method: String { return "/soseedy.SeedyFeatureFlags/SetAccountFeatureFlag" }
}


/// Instantiate Soseedy_SeedyFeatureFlagsServiceClient, then call methods of this protocol to make API calls.
public protocol Soseedy_SeedyFeatureFlagsService: ServiceClient {
  /// Synchronous. Unary.
  func setAccountFeatureFlag(_ request: Soseedy_SetAccountFeatureFlagRequest) throws -> Soseedy_FeatureFlag
  /// Asynchronous. Unary.
  func setAccountFeatureFlag(_ request: Soseedy_SetAccountFeatureFlagRequest, completion: @escaping (Soseedy_FeatureFlag?, CallResult) -> Void) throws -> Soseedy_SeedyFeatureFlagsSetAccountFeatureFlagCall

}

public final class Soseedy_SeedyFeatureFlagsServiceClient: ServiceClientBase, Soseedy_SeedyFeatureFlagsService {
  /// Synchronous. Unary.
  public func setAccountFeatureFlag(_ request: Soseedy_SetAccountFeatureFlagRequest) throws -> Soseedy_FeatureFlag {
    return try Soseedy_SeedyFeatureFlagsSetAccountFeatureFlagCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  public func setAccountFeatureFlag(_ request: Soseedy_SetAccountFeatureFlagRequest, completion: @escaping (Soseedy_FeatureFlag?, CallResult) -> Void) throws -> Soseedy_SeedyFeatureFlagsSetAccountFeatureFlagCall {
    return try Soseedy_SeedyFeatureFlagsSetAccountFeatureFlagCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

}

/// To build a server, implement a class that conforms to this protocol.
/// If one of the methods returning `ServerStatus?` returns nil,
/// it is expected that you have already returned a status to the client by means of `session.close`.
public protocol Soseedy_SeedyFeatureFlagsProvider: ServiceProvider {
  func setAccountFeatureFlag(request: Soseedy_SetAccountFeatureFlagRequest, session: Soseedy_SeedyFeatureFlagsSetAccountFeatureFlagSession) throws -> Soseedy_FeatureFlag
}

extension Soseedy_SeedyFeatureFlagsProvider {
  public var serviceName: String { return "soseedy.SeedyFeatureFlags" }

  /// Determines and calls the appropriate request handler, depending on the request's method.
  /// Throws `HandleMethodError.unknownMethod` for methods not handled by this service.
  public func handleMethod(_ method: String, handler: Handler) throws -> ServerStatus? {
    switch method {
    case "/soseedy.SeedyFeatureFlags/SetAccountFeatureFlag":
      return try Soseedy_SeedyFeatureFlagsSetAccountFeatureFlagSessionBase(
        handler: handler,
        providerBlock: { try self.setAccountFeatureFlag(request: $0, session: $1 as! Soseedy_SeedyFeatureFlagsSetAccountFeatureFlagSessionBase) })
          .run()
    default:
      throw HandleMethodError.unknownMethod
    }
  }
}

public protocol Soseedy_SeedyFeatureFlagsSetAccountFeatureFlagSession: ServerSessionUnary {}

fileprivate final class Soseedy_SeedyFeatureFlagsSetAccountFeatureFlagSessionBase: ServerSessionUnaryBase<Soseedy_SetAccountFeatureFlagRequest, Soseedy_FeatureFlag>, Soseedy_SeedyFeatureFlagsSetAccountFeatureFlagSession {}
