//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: observer.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import Dispatch
import SwiftGRPC
import SwiftProtobuf

public protocol Soseedy_SeedyObserversAddObserveeWithCredentialsCall: ClientCallUnary {}

fileprivate final class Soseedy_SeedyObserversAddObserveeWithCredentialsCallBase: ClientCallUnaryBase<Soseedy_AddObserveeWithCredentialsRequest, Soseedy_CanvasUser>, Soseedy_SeedyObserversAddObserveeWithCredentialsCall {
  override class var method: String { return "/soseedy.SeedyObservers/AddObserveeWithCredentials" }
}

public protocol Soseedy_SeedyObserversGetObserverAlertThresholdsCall: ClientCallUnary {}

fileprivate final class Soseedy_SeedyObserversGetObserverAlertThresholdsCallBase: ClientCallUnaryBase<Soseedy_GetObserverAlertThresholdsRequest, Soseedy_ObserverAlertThresholds>, Soseedy_SeedyObserversGetObserverAlertThresholdsCall {
  override class var method: String { return "/soseedy.SeedyObservers/GetObserverAlertThresholds" }
}

public protocol Soseedy_SeedyObserversAddObserverAlertThresholdCall: ClientCallUnary {}

fileprivate final class Soseedy_SeedyObserversAddObserverAlertThresholdCallBase: ClientCallUnaryBase<Soseedy_AddObserverAlertThresholdRequest, Soseedy_ObserverAlertThreshold>, Soseedy_SeedyObserversAddObserverAlertThresholdCall {
  override class var method: String { return "/soseedy.SeedyObservers/AddObserverAlertThreshold" }
}

public protocol Soseedy_SeedyObserversGetObserverAlertsCall: ClientCallUnary {}

fileprivate final class Soseedy_SeedyObserversGetObserverAlertsCallBase: ClientCallUnaryBase<Soseedy_GetObserverAlertsRequest, Soseedy_ObserverAlerts>, Soseedy_SeedyObserversGetObserverAlertsCall {
  override class var method: String { return "/soseedy.SeedyObservers/GetObserverAlerts" }
}


/// Instantiate Soseedy_SeedyObserversServiceClient, then call methods of this protocol to make API calls.
public protocol Soseedy_SeedyObserversService: ServiceClient {
  /// Synchronous. Unary.
  func addObserveeWithCredentials(_ request: Soseedy_AddObserveeWithCredentialsRequest) throws -> Soseedy_CanvasUser
  /// Asynchronous. Unary.
  func addObserveeWithCredentials(_ request: Soseedy_AddObserveeWithCredentialsRequest, completion: @escaping (Soseedy_CanvasUser?, CallResult) -> Void) throws -> Soseedy_SeedyObserversAddObserveeWithCredentialsCall

  /// Synchronous. Unary.
  func getObserverAlertThresholds(_ request: Soseedy_GetObserverAlertThresholdsRequest) throws -> Soseedy_ObserverAlertThresholds
  /// Asynchronous. Unary.
  func getObserverAlertThresholds(_ request: Soseedy_GetObserverAlertThresholdsRequest, completion: @escaping (Soseedy_ObserverAlertThresholds?, CallResult) -> Void) throws -> Soseedy_SeedyObserversGetObserverAlertThresholdsCall

  /// Synchronous. Unary.
  func addObserverAlertThreshold(_ request: Soseedy_AddObserverAlertThresholdRequest) throws -> Soseedy_ObserverAlertThreshold
  /// Asynchronous. Unary.
  func addObserverAlertThreshold(_ request: Soseedy_AddObserverAlertThresholdRequest, completion: @escaping (Soseedy_ObserverAlertThreshold?, CallResult) -> Void) throws -> Soseedy_SeedyObserversAddObserverAlertThresholdCall

  /// Synchronous. Unary.
  func getObserverAlerts(_ request: Soseedy_GetObserverAlertsRequest) throws -> Soseedy_ObserverAlerts
  /// Asynchronous. Unary.
  func getObserverAlerts(_ request: Soseedy_GetObserverAlertsRequest, completion: @escaping (Soseedy_ObserverAlerts?, CallResult) -> Void) throws -> Soseedy_SeedyObserversGetObserverAlertsCall

}

public final class Soseedy_SeedyObserversServiceClient: ServiceClientBase, Soseedy_SeedyObserversService {
  /// Synchronous. Unary.
  public func addObserveeWithCredentials(_ request: Soseedy_AddObserveeWithCredentialsRequest) throws -> Soseedy_CanvasUser {
    return try Soseedy_SeedyObserversAddObserveeWithCredentialsCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  public func addObserveeWithCredentials(_ request: Soseedy_AddObserveeWithCredentialsRequest, completion: @escaping (Soseedy_CanvasUser?, CallResult) -> Void) throws -> Soseedy_SeedyObserversAddObserveeWithCredentialsCall {
    return try Soseedy_SeedyObserversAddObserveeWithCredentialsCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  public func getObserverAlertThresholds(_ request: Soseedy_GetObserverAlertThresholdsRequest) throws -> Soseedy_ObserverAlertThresholds {
    return try Soseedy_SeedyObserversGetObserverAlertThresholdsCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  public func getObserverAlertThresholds(_ request: Soseedy_GetObserverAlertThresholdsRequest, completion: @escaping (Soseedy_ObserverAlertThresholds?, CallResult) -> Void) throws -> Soseedy_SeedyObserversGetObserverAlertThresholdsCall {
    return try Soseedy_SeedyObserversGetObserverAlertThresholdsCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  public func addObserverAlertThreshold(_ request: Soseedy_AddObserverAlertThresholdRequest) throws -> Soseedy_ObserverAlertThreshold {
    return try Soseedy_SeedyObserversAddObserverAlertThresholdCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  public func addObserverAlertThreshold(_ request: Soseedy_AddObserverAlertThresholdRequest, completion: @escaping (Soseedy_ObserverAlertThreshold?, CallResult) -> Void) throws -> Soseedy_SeedyObserversAddObserverAlertThresholdCall {
    return try Soseedy_SeedyObserversAddObserverAlertThresholdCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  public func getObserverAlerts(_ request: Soseedy_GetObserverAlertsRequest) throws -> Soseedy_ObserverAlerts {
    return try Soseedy_SeedyObserversGetObserverAlertsCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  public func getObserverAlerts(_ request: Soseedy_GetObserverAlertsRequest, completion: @escaping (Soseedy_ObserverAlerts?, CallResult) -> Void) throws -> Soseedy_SeedyObserversGetObserverAlertsCall {
    return try Soseedy_SeedyObserversGetObserverAlertsCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

}

/// To build a server, implement a class that conforms to this protocol.
/// If one of the methods returning `ServerStatus?` returns nil,
/// it is expected that you have already returned a status to the client by means of `session.close`.
public protocol Soseedy_SeedyObserversProvider: ServiceProvider {
  func addObserveeWithCredentials(request: Soseedy_AddObserveeWithCredentialsRequest, session: Soseedy_SeedyObserversAddObserveeWithCredentialsSession) throws -> Soseedy_CanvasUser
  func getObserverAlertThresholds(request: Soseedy_GetObserverAlertThresholdsRequest, session: Soseedy_SeedyObserversGetObserverAlertThresholdsSession) throws -> Soseedy_ObserverAlertThresholds
  func addObserverAlertThreshold(request: Soseedy_AddObserverAlertThresholdRequest, session: Soseedy_SeedyObserversAddObserverAlertThresholdSession) throws -> Soseedy_ObserverAlertThreshold
  func getObserverAlerts(request: Soseedy_GetObserverAlertsRequest, session: Soseedy_SeedyObserversGetObserverAlertsSession) throws -> Soseedy_ObserverAlerts
}

extension Soseedy_SeedyObserversProvider {
  public var serviceName: String { return "soseedy.SeedyObservers" }

  /// Determines and calls the appropriate request handler, depending on the request's method.
  /// Throws `HandleMethodError.unknownMethod` for methods not handled by this service.
  public func handleMethod(_ method: String, handler: Handler) throws -> ServerStatus? {
    switch method {
    case "/soseedy.SeedyObservers/AddObserveeWithCredentials":
      return try Soseedy_SeedyObserversAddObserveeWithCredentialsSessionBase(
        handler: handler,
        providerBlock: { try self.addObserveeWithCredentials(request: $0, session: $1 as! Soseedy_SeedyObserversAddObserveeWithCredentialsSessionBase) })
          .run()
    case "/soseedy.SeedyObservers/GetObserverAlertThresholds":
      return try Soseedy_SeedyObserversGetObserverAlertThresholdsSessionBase(
        handler: handler,
        providerBlock: { try self.getObserverAlertThresholds(request: $0, session: $1 as! Soseedy_SeedyObserversGetObserverAlertThresholdsSessionBase) })
          .run()
    case "/soseedy.SeedyObservers/AddObserverAlertThreshold":
      return try Soseedy_SeedyObserversAddObserverAlertThresholdSessionBase(
        handler: handler,
        providerBlock: { try self.addObserverAlertThreshold(request: $0, session: $1 as! Soseedy_SeedyObserversAddObserverAlertThresholdSessionBase) })
          .run()
    case "/soseedy.SeedyObservers/GetObserverAlerts":
      return try Soseedy_SeedyObserversGetObserverAlertsSessionBase(
        handler: handler,
        providerBlock: { try self.getObserverAlerts(request: $0, session: $1 as! Soseedy_SeedyObserversGetObserverAlertsSessionBase) })
          .run()
    default:
      throw HandleMethodError.unknownMethod
    }
  }
}

public protocol Soseedy_SeedyObserversAddObserveeWithCredentialsSession: ServerSessionUnary {}

fileprivate final class Soseedy_SeedyObserversAddObserveeWithCredentialsSessionBase: ServerSessionUnaryBase<Soseedy_AddObserveeWithCredentialsRequest, Soseedy_CanvasUser>, Soseedy_SeedyObserversAddObserveeWithCredentialsSession {}

public protocol Soseedy_SeedyObserversGetObserverAlertThresholdsSession: ServerSessionUnary {}

fileprivate final class Soseedy_SeedyObserversGetObserverAlertThresholdsSessionBase: ServerSessionUnaryBase<Soseedy_GetObserverAlertThresholdsRequest, Soseedy_ObserverAlertThresholds>, Soseedy_SeedyObserversGetObserverAlertThresholdsSession {}

public protocol Soseedy_SeedyObserversAddObserverAlertThresholdSession: ServerSessionUnary {}

fileprivate final class Soseedy_SeedyObserversAddObserverAlertThresholdSessionBase: ServerSessionUnaryBase<Soseedy_AddObserverAlertThresholdRequest, Soseedy_ObserverAlertThreshold>, Soseedy_SeedyObserversAddObserverAlertThresholdSession {}

public protocol Soseedy_SeedyObserversGetObserverAlertsSession: ServerSessionUnary {}

fileprivate final class Soseedy_SeedyObserversGetObserverAlertsSessionBase: ServerSessionUnaryBase<Soseedy_GetObserverAlertsRequest, Soseedy_ObserverAlerts>, Soseedy_SeedyObserversGetObserverAlertsSession {}
