---
name: TestsFoundation
options:
  bundleIdPrefix: com.instructure
  deploymentTarget:
    iOS: 14.0
settings:
  CODE_SIGN_STYLE: Automatic
  DEVELOPMENT_TEAM: B6333T4PXQ
  platform: iOS
packages:
  Swifter:
    url: https://github.com/httpswift/swifter
    branch: stable
projectReferences:
  Core:
    path: ../Core/Core.xcodeproj
targets:
  TestsFoundation:
    sources:
      - path: TestsFoundation
        createIntermediateGroups: true
    type: framework
    platform: iOS
    dependencies:
      - sdk: XCTest.framework
      - target: Core/Core
      - package: Swifter
schemes:
  TestsFoundation:
    build:
      targets:
        TestsFoundation: all
      
    