---
name: Core
attributes: {
  LastUpgradeCheck: "1600"
}
options:
  groupSortPosition: top
  bundleIdPrefix: com.instructure.icanvas
  deploymentTarget:
    iOS: 16.0
  createIntermediateGroups: true
settings:
  CODE_SIGN_STYLE: Automatic
  DEVELOPMENT_TEAM: B6333T4PXQ
  APPLICATION_EXTENSION_API_ONLY: true
  CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: true
  LOCALIZATION_PREFERS_STRING_CATALOGS: true
  ENABLE_USER_SCRIPT_SANDBOXING: true
  platform: iOS
packages:
  CombineSchedulers:
    url: https://github.com/pointfreeco/combine-schedulers
    exactVersion: 0.10.0
  CombineExt:
    url: https://github.com/CombineCommunity/CombineExt.git
    exactVersion: 1.8.1
  Lottie:
    url: https://github.com/airbnb/lottie-ios.git
    exactVersion: 3.5.0
  PSPDFKit:
    url: https://github.com/PSPDFKit/PSPDFKit-SP
    exactVersion: 13.9.1
  Swifter:
    url: https://github.com/httpswift/swifter
    version: 1.5.0
targets:
  Core:    
    type: framework
    platform: iOS
    sources:
      - path: Core
    dependencies:
      - package: CombineSchedulers
      - package: CombineExt
      - package: Lottie
      - package: PSPDFKit
    preBuildScripts:
      - path: ../scripts/xcode-build-phases/swiftLint.sh
        name: SwiftLint
        basedOnDependencyAnalysis: false
        inputFiles:
          - $(SRCROOT)/.swiftlint.yml
    settings:
      SWIFT_EMIT_LOC_STRINGS: true
  CoreTests:    
    type: bundle.unit-test
    platform: iOS
    settings:
      APPLICATION_EXTENSION_API_ONLY: false
      ENABLE_TESTABILITY: true
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/CoreTester.app/CoreTester
    sources:
      - path: CoreTests
    dependencies:
      - target: Core
      - target: TestsFoundation
  CoreTester:
    type: application
    platform: iOS
    transitivelyLinkDependencies: false
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.instructure.CoreTester
      CODE_SIGN_ENTITLEMENTS: CoreTester/CoreTester.entitlements
    sources:
      - path: CoreTester
    dependencies:
      - target: Core
  TestsFoundation:
    sources:
      - path: TestsFoundation
        createIntermediateGroups: true
    type: framework
    platform: iOS
    dependencies:
      - sdk: XCTest.framework
      - target: Core
      - package: Swifter
    preBuildScripts:
      - path: ../scripts/xcode-build-phases/swiftLint.sh
        name: SwiftLint
        basedOnDependencyAnalysis: false
        inputFiles:
          - $(SRCROOT)/.swiftlint.yml
schemes:
  Core:
    build:
      targets:
        Core: all
    test:
      targets: [CoreTests, CoreTester, TestsFoundation]
      testPlans:
        - path: ../TestPlans/CoreTests.xctestplan
          defaultPlan: true