project 'Canvas.xcodeproj'

source 'git@github.com:instructure/ios-podspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'Canvas' do
  use_frameworks!
  inhibit_all_warnings!
  pod 'JSTokenField', '~> 1.1'
  pod 'TBBModal'
  pod 'JSTokenField', '~> 1.1'
  pod 'Masonry'
  pod 'SVProgressHUD', '1.1.2'

  target 'TechDebt' do
    inherit! :search_paths
    pod 'JSTokenField', '~> 1.1'
    pod 'TBBModal'
    pod 'JSTokenField', '~> 1.1'
    pod 'Google/Analytics'
    pod 'Masonry'
    pod 'SVProgressHUD', '1.1.2'
  end
 
end
