---
name: Student
options:
  groupSortPosition: top
  bundleIdPrefix: com.instructure.icanvas
  deploymentTarget:
    iOS: 15.0
  createIntermediateGroups: true
settings:
  CODE_SIGN_STYLE: Automatic
  DEVELOPMENT_TEAM: B6333T4PXQ
  CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: true
  LOCALIZATION_PREFERS_STRING_CATALOGS: true
  CURRENT_PROJECT_VERSION: 1.0.0
  MARKETING_VERSION: 1.0.0
  platform: iOS
packages:
  Heap:
    url: https://github.com/heap/heap-ios-sdk.git
    exactVersion: 9.0.1
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    exactVersion: 8.12.1
  PSPDFKit:
    url: https://github.com/PSPDFKit/PSPDFKit-SP
    exactVersion: 13.0.1
projectReferences:
  CanvasCore:
    path: ../CanvasCore/CanvasCore.xcodeproj
  TestsFoundation:
    path: ../TestsFoundation/TestsFoundation.xcodeproj
  Core:
    path: ../Core/Core.xcodeproj
  Parent:
    path: ../Parent/Parent.xcodeproj
  Teacher:
    path: ../rn/Teacher/ios/Teacher.xcodeproj
targets:
  Student:    
    type: application
    platform: iOS
    transitivelyLinkDependencies: false
    settings:
      APPLICATION_EXTENSION_API_ONLY: false
      SWIFT_EMIT_LOC_STRINGS: true
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.instructure.icanvas
        INFOPLIST_FILE: Student/Info.plist
        CODE_SIGN_ENTITLEMENTS: Student/Student.entitlements
        TARGETED_DEVICE_FAMILY: 1,2
    sources:
      - path: Student
    dependencies:
      - package: PSPDFKit
      - package: Heap
      - target: CanvasCore/CanvasCore
      - target: Core/Core
      - target: SubmitAssignment
      - target: Widgets
    preBuildScripts:
      - path: ../scripts/swiftLint.sh
        name: SwiftLint
        basedOnDependencyAnalysis: false
      - path: ../scripts/startPackager.sh
        name: Start Packager
  SubmitAssignment:
    type: app-extension
    platform: iOS
    transitivelyLinkDependencies: true
    sources:
      - path: SubmitAssignment
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
      ENABLE_TESTABILITY: true
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.instructure.icanvas.SubmitAssignment
        INFOPLIST_FILE: SubmitAssignment/Info.plist
        CODE_SIGN_ENTITLEMENTS: SubmitAssignment/SubmitAssignment.entitlements
        TARGETED_DEVICE_FAMILY: 1,2
    dependencies:
      - package: Firebase
        product: FirebaseCrashlytics
      - target: Core/Core
  Widgets:
    type: app-extension
    platform: iOS
    transitivelyLinkDependencies: true
    sources:
      - path: Widgets
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
      ENABLE_TESTABILITY: true
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.instructure.icanvas.widgets
        INFOPLIST_FILE: Widgets/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Widgets/Resources/Widgets.entitlements
        TARGETED_DEVICE_FAMILY: 1,2
    dependencies:
      - target: Core/Core
  StudentUnitTests:    
    type: bundle.unit-test
    platform: iOS
    settings:
      APPLICATION_EXTENSION_API_ONLY: false
      ENABLE_TESTABILITY: true
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/Student.app/Student
    sources:
      - path: StudentUnitTests
  StudentE2ETests:    
    type: bundle.ui-testing
    platform: iOS
    settings:
      ENABLE_TESTABILITY: true
      TEST_TARGET_NAME: Student
    sources:
      - path: StudentE2ETests
    dependencies:
      - target: Core/Core
      - target: TestsFoundation/TestsFoundation
schemes:
  Student:
    build:
      targets:
        Student: all
  SubmitAssignment:
    build:
      targets:
        SubmitAssignment: all
  Widgets - Announcements:
    build:
      targets:
        Widgets: all
    run:
      targets:
        Widgets: all
      environmentVariables:
        _XCWidgetKind: AnnouncementsWidget
  Widgets - Grades:
    build:
      targets:
        Widgets: all
    run:
      targets:
        Widgets: all
      environmentVariables:
        _XCWidgetKind: GradesWidget
  E2ETests-Calendar:
    build:
      targets:
        Student: all
    test:
      targets: StudentE2ETests
      testPlans:
        - path: ../TestPlans/CalendarE2E.xctestplan
          defaultPlan: true
  E2ETests-iPad-Parent:
    build:
      targets:
        Parent/Parent: all
    test:
      targets: ParentE2ETests
      testPlans:
        - path: ../TestPlans/IPadParentTests.xctestplan
          defaultPlan: true
  E2ETests-iPad-Teacher:
    build:
      targets:
        Teacher/Teacher: all
    test:
      targets: TeacherE2ETests
      testPlans:
        - path: ../TestPlans/IPadTeacherTests.xctestplan
          defaultPlan: true
  E2ETests-iPad-Student:
    build:
      targets:
        Student: all
    test:
      targets: StudentE2ETests
      testPlans:
        - path: ../TestPlans/IPadStudentTests.xctestplan
          defaultPlan: true
  CITests:
    build:
      targets:
        Core/Core: all
        Core/CoreTester: all
        Parent/Parent: all
        Student: all
        Teacher/Teacher: all
        Core/CoreTests: test
        StudentUnitTests: test
        Teacher/TeacherTests: test
        Parent/ParentUnitTests: test
    test:
      targets: [Core/CoreTests, StudentUnitTests, Teacher/TeacherTests, Parent/ParentUnitTests]