---
name: Student
attributes: { LastUpgradeCheck: "1600" }
options:
  groupSortPosition: top
  bundleIdPrefix: com.instructure.icanvas
  deploymentTarget:
    iOS: 17.0
  createIntermediateGroups: true
settings:
  CODE_SIGN_STYLE: Automatic ## This line is removed in the project-ci.yml file so Bitrise can manage code sign.
  DEVELOPMENT_TEAM: B6333T4PXQ ## This line is removed in the project-ci.yml file so Bitrise can manage code sign.
  CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: true
  LOCALIZATION_PREFERS_STRING_CATALOGS: true
  ENABLE_USER_SCRIPT_SANDBOXING: true
  CURRENT_PROJECT_VERSION: 0.0.1
  MARKETING_VERSION: 0.0.1
  platform: iOS
sources:
  - path: ./
    excludes:
      - ".swiftlint.yml"
include:
  - Student/student.yml
  - SubmitAssignment/student-submit-assignment.yml
  - Widgets/student-widgets.yml
  - StudentE2ETests/student-e2e-tests.yml
  - StudentUnitTests/student-unit-tests.yml
projectReferences:
  Core:
    path: ../Core/Core.xcodeproj
packages:
  Pendo:
    url: https://github.com/pendo-io/pendo-mobile-sdk
    exactVersion: 3.6.1
  PSPDFKit:
    url: https://github.com/PSPDFKit/PSPDFKit-SP
    exactVersion: 13.9.1
  FirebaseCrashlytics:
    url: https://github.com/firebase/firebase-ios-sdk.git
    exactVersion: 10.23.1
  FirebaseRemoteConfig:
    url: https://github.com/firebase/firebase-ios-sdk.git
    exactVersion: 10.23.1
  FirebaseRemoteConfigSwift:
    url: https://github.com/firebase/firebase-ios-sdk.git
    exactVersion: 10.23.1
