disabled_rules: # rule identifiers to exclude from running
  - control_statement
  - class_delegate_protocol
  - todo
  - identifier_name
  - force_try
  - nesting
  - force_cast
  - xctfail_message
  - type_body_length
  - file_length
  - function_body_length
opt_in_rules: # some rules are only opt-in
  - yoda_condition
included: # paths to include during linting. `--path` is ignored if present.
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

line_length: 200

identifier_name:
  min_length: 1 # only min_length
  max_length: 50
  excluded: # excluded via string array
    - access_token
trailing_comma:
  mandatory_comma: true
