# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
  
  lane :tests do
    run_tests(workspace: "Canvas.xcworkspace", devices: ["iPhone 8"], scheme: "StudentUITests")
  end
  
  MY_XCODE_PROJECT_FILEPATH = File.absolute_path('Student/Student.xcodeproj')
  lane :sweep do
    test_run_block = lambda do |testrun_info|
      failed_test_count = testrun_info[:failed].size
    
      if failed_test_count > 0
        UI.important('The run of tests would finish with failures due to fragile tests here.')

        try_attempt = testrun_info[:try_count]
        if try_attempt < 3
          UI.header('Since we are using :multi_scan, we can re-run just those failing tests!')
        end
      end
    end
  
    result = multi_scan(
      workspace: 'Canvas.xcworkspace',
      devices: ["iPhone 8"],
      try_count: 3,
      fail_build: false,
      scheme: 'StudentUITests',
      testrun_completed_block: test_run_block,
      parallel_testrun_count: 4,
      batch_count: 30
    )
    unless result[:failed_testcount].zero?
      UI.message("There are #{result[:failed_testcount]} legitimate failing tests")
    end
  end
  
end
