# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
    prepare_certificates
  end

  private_lane :prepare_certificates do |options|
    sh("base64 -D -o Certificates.p12 <<< \"#{ENV['DISTRIBUTION_CERTIFICATE']}\"", log: false)
    create_keychain(
        name: "default_keychain",
        default_keychain: true,
        unlock: true,
        password: "default"
    )
    import_certificate(
      certificate_path: "fastlane/Certificates.p12",
      certificate_password: ENV['DISTRIBUTION_CERTIFICATE_PASSWORD'],
      keychain_name: "default_keychain",
      keychain_password: "default"
    )

    unlock_keychain(path:"default_keychain", password:"default")
    sh "security set-keychain-settings -t 3600 -l ~/Library/Keychains/default_keychain-db"
   

  desc "Tests lane"
  lane :hello_world do
    puts "Hello World!"
  end

end
