/*
 * DO NOT EDIT.
 *
 * Generated by the protocol buffer compiler.
 * Source: quizzes.proto
 *
 */

/*
 * Copyright 2018, gRPC Authors All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import Foundation
import Dispatch
import gRPC
import SwiftProtobuf

/// Type for errors thrown from generated client code.
internal enum Soseedy_SeedyQuizzesClientError : Error {
  case endOfStream
  case invalidMessageReceived
  case error(c: CallResult)
}

/// CreateQuiz (Unary)
internal class Soseedy_SeedyQuizzesCreateQuizCall {
  private var call : Call

  /// Create a call.
  fileprivate init(_ channel: Channel) {
    self.call = channel.makeCall("/soseedy.SeedyQuizzes/CreateQuiz")
  }

  /// Run the call. Blocks until the reply is received.
  fileprivate func run(request: Soseedy_CreateQuizRequest,
                       metadata: Metadata) throws -> Soseedy_Quiz {
    let sem = DispatchSemaphore(value: 0)
    var returnCallResult : CallResult!
    var returnResponse : Soseedy_Quiz?
    _ = try start(request:request, metadata:metadata) {response, callResult in
      returnResponse = response
      returnCallResult = callResult
      sem.signal()
    }
    _ = sem.wait(timeout: DispatchTime.distantFuture)
    if let returnResponse = returnResponse {
      return returnResponse
    } else {
      throw Soseedy_SeedyQuizzesClientError.error(c: returnCallResult)
    }
  }

  /// Start the call. Nonblocking.
  fileprivate func start(request: Soseedy_CreateQuizRequest,
                         metadata: Metadata,
                         completion: @escaping (Soseedy_Quiz?, CallResult)->())
    throws -> Soseedy_SeedyQuizzesCreateQuizCall {

      let requestData = try request.serializedData()
      try call.start(.unary,
                     metadata:metadata,
                     message:requestData)
      {(callResult) in
        if let responseData = callResult.resultData,
          let response = try? Soseedy_Quiz(serializedData:responseData) {
          completion(response, callResult)
        } else {
          completion(nil, callResult)
        }
      }
      return self
  }

  /// Cancel the call.
  internal func cancel() {
    call.cancel()
  }
}

/// CreateQuizSubmission (Unary)
internal class Soseedy_SeedyQuizzesCreateQuizSubmissionCall {
  private var call : Call

  /// Create a call.
  fileprivate init(_ channel: Channel) {
    self.call = channel.makeCall("/soseedy.SeedyQuizzes/CreateQuizSubmission")
  }

  /// Run the call. Blocks until the reply is received.
  fileprivate func run(request: Soseedy_CreateQuizSubmissionRequest,
                       metadata: Metadata) throws -> Soseedy_QuizSubmission {
    let sem = DispatchSemaphore(value: 0)
    var returnCallResult : CallResult!
    var returnResponse : Soseedy_QuizSubmission?
    _ = try start(request:request, metadata:metadata) {response, callResult in
      returnResponse = response
      returnCallResult = callResult
      sem.signal()
    }
    _ = sem.wait(timeout: DispatchTime.distantFuture)
    if let returnResponse = returnResponse {
      return returnResponse
    } else {
      throw Soseedy_SeedyQuizzesClientError.error(c: returnCallResult)
    }
  }

  /// Start the call. Nonblocking.
  fileprivate func start(request: Soseedy_CreateQuizSubmissionRequest,
                         metadata: Metadata,
                         completion: @escaping (Soseedy_QuizSubmission?, CallResult)->())
    throws -> Soseedy_SeedyQuizzesCreateQuizSubmissionCall {

      let requestData = try request.serializedData()
      try call.start(.unary,
                     metadata:metadata,
                     message:requestData)
      {(callResult) in
        if let responseData = callResult.resultData,
          let response = try? Soseedy_QuizSubmission(serializedData:responseData) {
          completion(response, callResult)
        } else {
          completion(nil, callResult)
        }
      }
      return self
  }

  /// Cancel the call.
  internal func cancel() {
    call.cancel()
  }
}

/// CompleteQuizSubmission (Unary)
internal class Soseedy_SeedyQuizzesCompleteQuizSubmissionCall {
  private var call : Call

  /// Create a call.
  fileprivate init(_ channel: Channel) {
    self.call = channel.makeCall("/soseedy.SeedyQuizzes/CompleteQuizSubmission")
  }

  /// Run the call. Blocks until the reply is received.
  fileprivate func run(request: Soseedy_CompleteQuizSubmissionRequest,
                       metadata: Metadata) throws -> Soseedy_QuizSubmission {
    let sem = DispatchSemaphore(value: 0)
    var returnCallResult : CallResult!
    var returnResponse : Soseedy_QuizSubmission?
    _ = try start(request:request, metadata:metadata) {response, callResult in
      returnResponse = response
      returnCallResult = callResult
      sem.signal()
    }
    _ = sem.wait(timeout: DispatchTime.distantFuture)
    if let returnResponse = returnResponse {
      return returnResponse
    } else {
      throw Soseedy_SeedyQuizzesClientError.error(c: returnCallResult)
    }
  }

  /// Start the call. Nonblocking.
  fileprivate func start(request: Soseedy_CompleteQuizSubmissionRequest,
                         metadata: Metadata,
                         completion: @escaping (Soseedy_QuizSubmission?, CallResult)->())
    throws -> Soseedy_SeedyQuizzesCompleteQuizSubmissionCall {

      let requestData = try request.serializedData()
      try call.start(.unary,
                     metadata:metadata,
                     message:requestData)
      {(callResult) in
        if let responseData = callResult.resultData,
          let response = try? Soseedy_QuizSubmission(serializedData:responseData) {
          completion(response, callResult)
        } else {
          completion(nil, callResult)
        }
      }
      return self
  }

  /// Cancel the call.
  internal func cancel() {
    call.cancel()
  }
}

/// CreateQuizQuestion (Unary)
internal class Soseedy_SeedyQuizzesCreateQuizQuestionCall {
  private var call : Call

  /// Create a call.
  fileprivate init(_ channel: Channel) {
    self.call = channel.makeCall("/soseedy.SeedyQuizzes/CreateQuizQuestion")
  }

  /// Run the call. Blocks until the reply is received.
  fileprivate func run(request: Soseedy_CreateQuizQuestionRequest,
                       metadata: Metadata) throws -> Soseedy_CreateQuizQuestionResponse {
    let sem = DispatchSemaphore(value: 0)
    var returnCallResult : CallResult!
    var returnResponse : Soseedy_CreateQuizQuestionResponse?
    _ = try start(request:request, metadata:metadata) {response, callResult in
      returnResponse = response
      returnCallResult = callResult
      sem.signal()
    }
    _ = sem.wait(timeout: DispatchTime.distantFuture)
    if let returnResponse = returnResponse {
      return returnResponse
    } else {
      throw Soseedy_SeedyQuizzesClientError.error(c: returnCallResult)
    }
  }

  /// Start the call. Nonblocking.
  fileprivate func start(request: Soseedy_CreateQuizQuestionRequest,
                         metadata: Metadata,
                         completion: @escaping (Soseedy_CreateQuizQuestionResponse?, CallResult)->())
    throws -> Soseedy_SeedyQuizzesCreateQuizQuestionCall {

      let requestData = try request.serializedData()
      try call.start(.unary,
                     metadata:metadata,
                     message:requestData)
      {(callResult) in
        if let responseData = callResult.resultData,
          let response = try? Soseedy_CreateQuizQuestionResponse(serializedData:responseData) {
          completion(response, callResult)
        } else {
          completion(nil, callResult)
        }
      }
      return self
  }

  /// Cancel the call.
  internal func cancel() {
    call.cancel()
  }
}

/// PublishQuiz (Unary)
internal class Soseedy_SeedyQuizzesPublishQuizCall {
  private var call : Call

  /// Create a call.
  fileprivate init(_ channel: Channel) {
    self.call = channel.makeCall("/soseedy.SeedyQuizzes/PublishQuiz")
  }

  /// Run the call. Blocks until the reply is received.
  fileprivate func run(request: Soseedy_PublishQuizRequest,
                       metadata: Metadata) throws -> Soseedy_Quiz {
    let sem = DispatchSemaphore(value: 0)
    var returnCallResult : CallResult!
    var returnResponse : Soseedy_Quiz?
    _ = try start(request:request, metadata:metadata) {response, callResult in
      returnResponse = response
      returnCallResult = callResult
      sem.signal()
    }
    _ = sem.wait(timeout: DispatchTime.distantFuture)
    if let returnResponse = returnResponse {
      return returnResponse
    } else {
      throw Soseedy_SeedyQuizzesClientError.error(c: returnCallResult)
    }
  }

  /// Start the call. Nonblocking.
  fileprivate func start(request: Soseedy_PublishQuizRequest,
                         metadata: Metadata,
                         completion: @escaping (Soseedy_Quiz?, CallResult)->())
    throws -> Soseedy_SeedyQuizzesPublishQuizCall {

      let requestData = try request.serializedData()
      try call.start(.unary,
                     metadata:metadata,
                     message:requestData)
      {(callResult) in
        if let responseData = callResult.resultData,
          let response = try? Soseedy_Quiz(serializedData:responseData) {
          completion(response, callResult)
        } else {
          completion(nil, callResult)
        }
      }
      return self
  }

  /// Cancel the call.
  internal func cancel() {
    call.cancel()
  }
}

/// SeedQuizzes (Unary)
internal class Soseedy_SeedyQuizzesSeedQuizzesCall {
  private var call : Call

  /// Create a call.
  fileprivate init(_ channel: Channel) {
    self.call = channel.makeCall("/soseedy.SeedyQuizzes/SeedQuizzes")
  }

  /// Run the call. Blocks until the reply is received.
  fileprivate func run(request: Soseedy_SeedQuizzesRequest,
                       metadata: Metadata) throws -> Soseedy_Quizzes {
    let sem = DispatchSemaphore(value: 0)
    var returnCallResult : CallResult!
    var returnResponse : Soseedy_Quizzes?
    _ = try start(request:request, metadata:metadata) {response, callResult in
      returnResponse = response
      returnCallResult = callResult
      sem.signal()
    }
    _ = sem.wait(timeout: DispatchTime.distantFuture)
    if let returnResponse = returnResponse {
      return returnResponse
    } else {
      throw Soseedy_SeedyQuizzesClientError.error(c: returnCallResult)
    }
  }

  /// Start the call. Nonblocking.
  fileprivate func start(request: Soseedy_SeedQuizzesRequest,
                         metadata: Metadata,
                         completion: @escaping (Soseedy_Quizzes?, CallResult)->())
    throws -> Soseedy_SeedyQuizzesSeedQuizzesCall {

      let requestData = try request.serializedData()
      try call.start(.unary,
                     metadata:metadata,
                     message:requestData)
      {(callResult) in
        if let responseData = callResult.resultData,
          let response = try? Soseedy_Quizzes(serializedData:responseData) {
          completion(response, callResult)
        } else {
          completion(nil, callResult)
        }
      }
      return self
  }

  /// Cancel the call.
  internal func cancel() {
    call.cancel()
  }
}

/// SeedQuizSubmission (Unary)
internal class Soseedy_SeedyQuizzesSeedQuizSubmissionCall {
  private var call : Call

  /// Create a call.
  fileprivate init(_ channel: Channel) {
    self.call = channel.makeCall("/soseedy.SeedyQuizzes/SeedQuizSubmission")
  }

  /// Run the call. Blocks until the reply is received.
  fileprivate func run(request: Soseedy_SeedQuizSubmissionRequest,
                       metadata: Metadata) throws -> Soseedy_QuizSubmission {
    let sem = DispatchSemaphore(value: 0)
    var returnCallResult : CallResult!
    var returnResponse : Soseedy_QuizSubmission?
    _ = try start(request:request, metadata:metadata) {response, callResult in
      returnResponse = response
      returnCallResult = callResult
      sem.signal()
    }
    _ = sem.wait(timeout: DispatchTime.distantFuture)
    if let returnResponse = returnResponse {
      return returnResponse
    } else {
      throw Soseedy_SeedyQuizzesClientError.error(c: returnCallResult)
    }
  }

  /// Start the call. Nonblocking.
  fileprivate func start(request: Soseedy_SeedQuizSubmissionRequest,
                         metadata: Metadata,
                         completion: @escaping (Soseedy_QuizSubmission?, CallResult)->())
    throws -> Soseedy_SeedyQuizzesSeedQuizSubmissionCall {

      let requestData = try request.serializedData()
      try call.start(.unary,
                     metadata:metadata,
                     message:requestData)
      {(callResult) in
        if let responseData = callResult.resultData,
          let response = try? Soseedy_QuizSubmission(serializedData:responseData) {
          completion(response, callResult)
        } else {
          completion(nil, callResult)
        }
      }
      return self
  }

  /// Cancel the call.
  internal func cancel() {
    call.cancel()
  }
}

/// Call methods of this class to make API calls.
internal class Soseedy_SeedyQuizzesService {
  public var channel: Channel

  /// This metadata will be sent with all requests.
  internal var metadata : Metadata

  /// This property allows the service host name to be overridden.
  /// For example, it can be used to make calls to "localhost:8080"
  /// appear to be to "example.com".
  internal var host : String {
    get {
      return self.channel.host
    }
    set {
      self.channel.host = newValue
    }
  }

  /// Create a client.
  internal init(address: String, secure: Bool = true) {
    gRPC.initialize()
    channel = Channel(address:address, secure:secure)
    metadata = Metadata()
  }

  /// Create a client that makes secure connections with a custom certificate and (optional) hostname.
  internal init(address: String, certificates: String, host: String?) {
    gRPC.initialize()
    channel = Channel(address:address, certificates:certificates, host:host)
    metadata = Metadata()
  }

  /// Synchronous. Unary.
  internal func createquiz(_ request: Soseedy_CreateQuizRequest)
    throws
    -> Soseedy_Quiz {
      return try Soseedy_SeedyQuizzesCreateQuizCall(channel).run(request:request, metadata:metadata)
  }
  /// Asynchronous. Unary.
  internal func createquiz(_ request: Soseedy_CreateQuizRequest,
                  completion: @escaping (Soseedy_Quiz?, CallResult)->())
    throws
    -> Soseedy_SeedyQuizzesCreateQuizCall {
      return try Soseedy_SeedyQuizzesCreateQuizCall(channel).start(request:request,
                                                 metadata:metadata,
                                                 completion:completion)
  }
  /// Synchronous. Unary.
  internal func createquizsubmission(_ request: Soseedy_CreateQuizSubmissionRequest)
    throws
    -> Soseedy_QuizSubmission {
      return try Soseedy_SeedyQuizzesCreateQuizSubmissionCall(channel).run(request:request, metadata:metadata)
  }
  /// Asynchronous. Unary.
  internal func createquizsubmission(_ request: Soseedy_CreateQuizSubmissionRequest,
                  completion: @escaping (Soseedy_QuizSubmission?, CallResult)->())
    throws
    -> Soseedy_SeedyQuizzesCreateQuizSubmissionCall {
      return try Soseedy_SeedyQuizzesCreateQuizSubmissionCall(channel).start(request:request,
                                                 metadata:metadata,
                                                 completion:completion)
  }
  /// Synchronous. Unary.
  internal func completequizsubmission(_ request: Soseedy_CompleteQuizSubmissionRequest)
    throws
    -> Soseedy_QuizSubmission {
      return try Soseedy_SeedyQuizzesCompleteQuizSubmissionCall(channel).run(request:request, metadata:metadata)
  }
  /// Asynchronous. Unary.
  internal func completequizsubmission(_ request: Soseedy_CompleteQuizSubmissionRequest,
                  completion: @escaping (Soseedy_QuizSubmission?, CallResult)->())
    throws
    -> Soseedy_SeedyQuizzesCompleteQuizSubmissionCall {
      return try Soseedy_SeedyQuizzesCompleteQuizSubmissionCall(channel).start(request:request,
                                                 metadata:metadata,
                                                 completion:completion)
  }
  /// Synchronous. Unary.
  internal func createquizquestion(_ request: Soseedy_CreateQuizQuestionRequest)
    throws
    -> Soseedy_CreateQuizQuestionResponse {
      return try Soseedy_SeedyQuizzesCreateQuizQuestionCall(channel).run(request:request, metadata:metadata)
  }
  /// Asynchronous. Unary.
  internal func createquizquestion(_ request: Soseedy_CreateQuizQuestionRequest,
                  completion: @escaping (Soseedy_CreateQuizQuestionResponse?, CallResult)->())
    throws
    -> Soseedy_SeedyQuizzesCreateQuizQuestionCall {
      return try Soseedy_SeedyQuizzesCreateQuizQuestionCall(channel).start(request:request,
                                                 metadata:metadata,
                                                 completion:completion)
  }
  /// Synchronous. Unary.
  internal func publishquiz(_ request: Soseedy_PublishQuizRequest)
    throws
    -> Soseedy_Quiz {
      return try Soseedy_SeedyQuizzesPublishQuizCall(channel).run(request:request, metadata:metadata)
  }
  /// Asynchronous. Unary.
  internal func publishquiz(_ request: Soseedy_PublishQuizRequest,
                  completion: @escaping (Soseedy_Quiz?, CallResult)->())
    throws
    -> Soseedy_SeedyQuizzesPublishQuizCall {
      return try Soseedy_SeedyQuizzesPublishQuizCall(channel).start(request:request,
                                                 metadata:metadata,
                                                 completion:completion)
  }
  /// Synchronous. Unary.
  internal func seedquizzes(_ request: Soseedy_SeedQuizzesRequest)
    throws
    -> Soseedy_Quizzes {
      return try Soseedy_SeedyQuizzesSeedQuizzesCall(channel).run(request:request, metadata:metadata)
  }
  /// Asynchronous. Unary.
  internal func seedquizzes(_ request: Soseedy_SeedQuizzesRequest,
                  completion: @escaping (Soseedy_Quizzes?, CallResult)->())
    throws
    -> Soseedy_SeedyQuizzesSeedQuizzesCall {
      return try Soseedy_SeedyQuizzesSeedQuizzesCall(channel).start(request:request,
                                                 metadata:metadata,
                                                 completion:completion)
  }
  /// Synchronous. Unary.
  internal func seedquizsubmission(_ request: Soseedy_SeedQuizSubmissionRequest)
    throws
    -> Soseedy_QuizSubmission {
      return try Soseedy_SeedyQuizzesSeedQuizSubmissionCall(channel).run(request:request, metadata:metadata)
  }
  /// Asynchronous. Unary.
  internal func seedquizsubmission(_ request: Soseedy_SeedQuizSubmissionRequest,
                  completion: @escaping (Soseedy_QuizSubmission?, CallResult)->())
    throws
    -> Soseedy_SeedyQuizzesSeedQuizSubmissionCall {
      return try Soseedy_SeedyQuizzesSeedQuizSubmissionCall(channel).start(request:request,
                                                 metadata:metadata,
                                                 completion:completion)
  }
}


/// Type for errors thrown from generated server code.
internal enum Soseedy_SeedyQuizzesServerError : Error {
  case endOfStream
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Soseedy_SeedyQuizzesProvider {
  func createquiz(request : Soseedy_CreateQuizRequest, session : Soseedy_SeedyQuizzesCreateQuizSession) throws -> Soseedy_Quiz
  func createquizsubmission(request : Soseedy_CreateQuizSubmissionRequest, session : Soseedy_SeedyQuizzesCreateQuizSubmissionSession) throws -> Soseedy_QuizSubmission
  func completequizsubmission(request : Soseedy_CompleteQuizSubmissionRequest, session : Soseedy_SeedyQuizzesCompleteQuizSubmissionSession) throws -> Soseedy_QuizSubmission
  func createquizquestion(request : Soseedy_CreateQuizQuestionRequest, session : Soseedy_SeedyQuizzesCreateQuizQuestionSession) throws -> Soseedy_CreateQuizQuestionResponse
  func publishquiz(request : Soseedy_PublishQuizRequest, session : Soseedy_SeedyQuizzesPublishQuizSession) throws -> Soseedy_Quiz
  func seedquizzes(request : Soseedy_SeedQuizzesRequest, session : Soseedy_SeedyQuizzesSeedQuizzesSession) throws -> Soseedy_Quizzes
  func seedquizsubmission(request : Soseedy_SeedQuizSubmissionRequest, session : Soseedy_SeedyQuizzesSeedQuizSubmissionSession) throws -> Soseedy_QuizSubmission
}

/// Common properties available in each service session.
internal class Soseedy_SeedyQuizzesSession {
  fileprivate var handler : gRPC.Handler
  internal var requestMetadata : Metadata { return handler.requestMetadata }

  internal var statusCode : Int = 0
  internal var statusMessage : String = "OK"
  internal var initialMetadata : Metadata = Metadata()
  internal var trailingMetadata : Metadata = Metadata()

  fileprivate init(handler:gRPC.Handler) {
    self.handler = handler
  }
}

// CreateQuiz (Unary)
internal class Soseedy_SeedyQuizzesCreateQuizSession : Soseedy_SeedyQuizzesSession {
  private var provider : Soseedy_SeedyQuizzesProvider

  /// Create a session.
  fileprivate init(handler:gRPC.Handler, provider: Soseedy_SeedyQuizzesProvider) {
    self.provider = provider
    super.init(handler:handler)
  }

  /// Run the session. Internal.
  fileprivate func run(queue:DispatchQueue) throws {
    try handler.receiveMessage(initialMetadata:initialMetadata) {(requestData) in
      if let requestData = requestData {
        let requestMessage = try Soseedy_CreateQuizRequest(serializedData:requestData)
        let replyMessage = try self.provider.createquiz(request:requestMessage, session: self)
        try self.handler.sendResponse(message:replyMessage.serializedData(),
                                      statusCode:self.statusCode,
                                      statusMessage:self.statusMessage,
                                      trailingMetadata:self.trailingMetadata)
      }
    }
  }
}

// CreateQuizSubmission (Unary)
internal class Soseedy_SeedyQuizzesCreateQuizSubmissionSession : Soseedy_SeedyQuizzesSession {
  private var provider : Soseedy_SeedyQuizzesProvider

  /// Create a session.
  fileprivate init(handler:gRPC.Handler, provider: Soseedy_SeedyQuizzesProvider) {
    self.provider = provider
    super.init(handler:handler)
  }

  /// Run the session. Internal.
  fileprivate func run(queue:DispatchQueue) throws {
    try handler.receiveMessage(initialMetadata:initialMetadata) {(requestData) in
      if let requestData = requestData {
        let requestMessage = try Soseedy_CreateQuizSubmissionRequest(serializedData:requestData)
        let replyMessage = try self.provider.createquizsubmission(request:requestMessage, session: self)
        try self.handler.sendResponse(message:replyMessage.serializedData(),
                                      statusCode:self.statusCode,
                                      statusMessage:self.statusMessage,
                                      trailingMetadata:self.trailingMetadata)
      }
    }
  }
}

// CompleteQuizSubmission (Unary)
internal class Soseedy_SeedyQuizzesCompleteQuizSubmissionSession : Soseedy_SeedyQuizzesSession {
  private var provider : Soseedy_SeedyQuizzesProvider

  /// Create a session.
  fileprivate init(handler:gRPC.Handler, provider: Soseedy_SeedyQuizzesProvider) {
    self.provider = provider
    super.init(handler:handler)
  }

  /// Run the session. Internal.
  fileprivate func run(queue:DispatchQueue) throws {
    try handler.receiveMessage(initialMetadata:initialMetadata) {(requestData) in
      if let requestData = requestData {
        let requestMessage = try Soseedy_CompleteQuizSubmissionRequest(serializedData:requestData)
        let replyMessage = try self.provider.completequizsubmission(request:requestMessage, session: self)
        try self.handler.sendResponse(message:replyMessage.serializedData(),
                                      statusCode:self.statusCode,
                                      statusMessage:self.statusMessage,
                                      trailingMetadata:self.trailingMetadata)
      }
    }
  }
}

// CreateQuizQuestion (Unary)
internal class Soseedy_SeedyQuizzesCreateQuizQuestionSession : Soseedy_SeedyQuizzesSession {
  private var provider : Soseedy_SeedyQuizzesProvider

  /// Create a session.
  fileprivate init(handler:gRPC.Handler, provider: Soseedy_SeedyQuizzesProvider) {
    self.provider = provider
    super.init(handler:handler)
  }

  /// Run the session. Internal.
  fileprivate func run(queue:DispatchQueue) throws {
    try handler.receiveMessage(initialMetadata:initialMetadata) {(requestData) in
      if let requestData = requestData {
        let requestMessage = try Soseedy_CreateQuizQuestionRequest(serializedData:requestData)
        let replyMessage = try self.provider.createquizquestion(request:requestMessage, session: self)
        try self.handler.sendResponse(message:replyMessage.serializedData(),
                                      statusCode:self.statusCode,
                                      statusMessage:self.statusMessage,
                                      trailingMetadata:self.trailingMetadata)
      }
    }
  }
}

// PublishQuiz (Unary)
internal class Soseedy_SeedyQuizzesPublishQuizSession : Soseedy_SeedyQuizzesSession {
  private var provider : Soseedy_SeedyQuizzesProvider

  /// Create a session.
  fileprivate init(handler:gRPC.Handler, provider: Soseedy_SeedyQuizzesProvider) {
    self.provider = provider
    super.init(handler:handler)
  }

  /// Run the session. Internal.
  fileprivate func run(queue:DispatchQueue) throws {
    try handler.receiveMessage(initialMetadata:initialMetadata) {(requestData) in
      if let requestData = requestData {
        let requestMessage = try Soseedy_PublishQuizRequest(serializedData:requestData)
        let replyMessage = try self.provider.publishquiz(request:requestMessage, session: self)
        try self.handler.sendResponse(message:replyMessage.serializedData(),
                                      statusCode:self.statusCode,
                                      statusMessage:self.statusMessage,
                                      trailingMetadata:self.trailingMetadata)
      }
    }
  }
}

// SeedQuizzes (Unary)
internal class Soseedy_SeedyQuizzesSeedQuizzesSession : Soseedy_SeedyQuizzesSession {
  private var provider : Soseedy_SeedyQuizzesProvider

  /// Create a session.
  fileprivate init(handler:gRPC.Handler, provider: Soseedy_SeedyQuizzesProvider) {
    self.provider = provider
    super.init(handler:handler)
  }

  /// Run the session. Internal.
  fileprivate func run(queue:DispatchQueue) throws {
    try handler.receiveMessage(initialMetadata:initialMetadata) {(requestData) in
      if let requestData = requestData {
        let requestMessage = try Soseedy_SeedQuizzesRequest(serializedData:requestData)
        let replyMessage = try self.provider.seedquizzes(request:requestMessage, session: self)
        try self.handler.sendResponse(message:replyMessage.serializedData(),
                                      statusCode:self.statusCode,
                                      statusMessage:self.statusMessage,
                                      trailingMetadata:self.trailingMetadata)
      }
    }
  }
}

// SeedQuizSubmission (Unary)
internal class Soseedy_SeedyQuizzesSeedQuizSubmissionSession : Soseedy_SeedyQuizzesSession {
  private var provider : Soseedy_SeedyQuizzesProvider

  /// Create a session.
  fileprivate init(handler:gRPC.Handler, provider: Soseedy_SeedyQuizzesProvider) {
    self.provider = provider
    super.init(handler:handler)
  }

  /// Run the session. Internal.
  fileprivate func run(queue:DispatchQueue) throws {
    try handler.receiveMessage(initialMetadata:initialMetadata) {(requestData) in
      if let requestData = requestData {
        let requestMessage = try Soseedy_SeedQuizSubmissionRequest(serializedData:requestData)
        let replyMessage = try self.provider.seedquizsubmission(request:requestMessage, session: self)
        try self.handler.sendResponse(message:replyMessage.serializedData(),
                                      statusCode:self.statusCode,
                                      statusMessage:self.statusMessage,
                                      trailingMetadata:self.trailingMetadata)
      }
    }
  }
}


/// Main server for generated service
internal class Soseedy_SeedyQuizzesServer {
  private var address: String
  private var server: gRPC.Server
  private var provider: Soseedy_SeedyQuizzesProvider?

  /// Create a server that accepts insecure connections.
  internal init(address:String,
              provider:Soseedy_SeedyQuizzesProvider) {
    gRPC.initialize()
    self.address = address
    self.provider = provider
    self.server = gRPC.Server(address:address)
  }

  /// Create a server that accepts secure connections.
  internal init?(address:String,
               certificateURL:URL,
               keyURL:URL,
               provider:Soseedy_SeedyQuizzesProvider) {
    gRPC.initialize()
    self.address = address
    self.provider = provider
    guard
      let certificate = try? String(contentsOf: certificateURL, encoding: .utf8),
      let key = try? String(contentsOf: keyURL, encoding: .utf8)
      else {
        return nil
    }
    self.server = gRPC.Server(address:address, key:key, certs:certificate)
  }

  /// Start the server.
  internal func start(queue:DispatchQueue = DispatchQueue.global()) {
    guard let provider = self.provider else {
      fatalError() // the server requires a provider
    }
    server.run {(handler) in
      print("Server received request to " + handler.host
        + " calling " + handler.method
        + " from " + handler.caller
        + " with " + String(describing:handler.requestMetadata) )

      do {
        switch handler.method {
        case "/soseedy.SeedyQuizzes/CreateQuiz":
          try Soseedy_SeedyQuizzesCreateQuizSession(handler:handler, provider:provider).run(queue:queue)
        case "/soseedy.SeedyQuizzes/CreateQuizSubmission":
          try Soseedy_SeedyQuizzesCreateQuizSubmissionSession(handler:handler, provider:provider).run(queue:queue)
        case "/soseedy.SeedyQuizzes/CompleteQuizSubmission":
          try Soseedy_SeedyQuizzesCompleteQuizSubmissionSession(handler:handler, provider:provider).run(queue:queue)
        case "/soseedy.SeedyQuizzes/CreateQuizQuestion":
          try Soseedy_SeedyQuizzesCreateQuizQuestionSession(handler:handler, provider:provider).run(queue:queue)
        case "/soseedy.SeedyQuizzes/PublishQuiz":
          try Soseedy_SeedyQuizzesPublishQuizSession(handler:handler, provider:provider).run(queue:queue)
        case "/soseedy.SeedyQuizzes/SeedQuizzes":
          try Soseedy_SeedyQuizzesSeedQuizzesSession(handler:handler, provider:provider).run(queue:queue)
        case "/soseedy.SeedyQuizzes/SeedQuizSubmission":
          try Soseedy_SeedyQuizzesSeedQuizSubmissionSession(handler:handler, provider:provider).run(queue:queue)
        default:
          break // handle unknown requests
        }
      } catch (let error) {
        print("Server error: \(error)")
      }
    }
  }
}

